In [2]:
import sys
import os

project_root = os.path.abspath('..')
if project_root not in sys.path:
    sys.path.insert(0, project_root)

In [3]:
import tz_pypsa
import pandas as pd
import numpy as np
from tz_pypsa.model import Model
import tz_pypsa.wrangle as wrangle

In [4]:
n=Model.load_csv_from_dir('../stock_models/Japan',
                          year=2023,
                          frequency='1h',
                          timesteps=8760,
                          backstop=False)

WARNING:pypsa.io:Importing network from PyPSA version v? while current version is v0.33.0. Read the release notes at https://pypsa.readthedocs.io/en/latest/release_notes.html to prepare your network for import.
INFO:pypsa.networks:Repeating time-series for each investment period and converting snapshots to a pandas.MultiIndex.
INFO:pypsa.io:Imported network Japan has buses, carriers, generators, links, loads, storage_units

In [5]:
n.optimize()

WARNING:pypsa.consistency:The following buses have carriers which are not defined:
Index(['JPN01', 'JPN02', 'JPN03', 'JPN04', 'JPN05', 'JPN06', 'JPN07', 'JPN08',
       'JPN09'],
      dtype='object', name='Bus')
INFO:linopy.model: Solve problem using Highs solver
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 14/14 [00:30<00:00,  2.16s/it]
Writing continuous variables.: 100%|██████████| 5/5 [00:06<00:00,  1.20s/it]
INFO:linopy.io: Writing time: 37.26s
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 2084880 primals, 4801371 duals
Objective: 3.52e+10
Solver model: available
Solver message: optimal

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Generator-fix-p-ramp_limit_up, Link-fix-p-lower, Link-fix-p-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-state_of_charge_set, StorageUnit-energy_balance were not assigned to the network.

('ok', 'optimal')

In [19]:
n.statistics()

                                           Optimal Capacity  \
                                                       2023
Generator   Biomass                              6236.98000
            Blue ammonia & coal co-firing               NaN
            Blue hydrogen & gas co-firing               NaN
            Coal                                45592.00000
            Gas                                 73544.00000
            Geothermal                            457.50000
            Green ammonia & coal co-firing              NaN
            Green hydrogen & gas co-firing              NaN
            Hydro conventional                  19996.80000
            Nuclear                             30530.00000
            Offshore wind                               NaN
            Oil                                 19795.00000
            Onshore wind                         4395.00000
            Solar grid-scale                    65650.98182
Link        Transmission                        40080.00000
Load        -                                       0.00000
StorageUnit Battery storage                       195.00000
            Pumped hydro                        26446.00000

                                           Installed Capacity        Supply  \
                                                         2023          2023
Generator   Biomass                                6236.98000  2.794947e+07
            Blue ammonia & coal co-firing                 NaN           NaN
            Blue hydrogen & gas co-firing                 NaN           NaN
            Coal                                  45592.00000  3.499852e+08
            Gas                                   73544.00000  2.179211e+08
            Geothermal                              457.50000  1.890777e+06
            Green ammonia & coal co-firing                NaN           NaN
            Green hydrogen & gas co-firing                NaN           NaN
            Hydro conventional                    19996.80000  6.832994e+07
            Nuclear                               30530.00000  7.717479e+07
            Offshore wind                                 NaN           NaN
            Oil                                   19795.00000  3.694876e+03
            Onshore wind                           4395.00000  9.143532e+06
            Solar grid-scale                      65650.98182  1.011240e+08
Link        Transmission                          40080.00000  5.992911e+07
Load        -                                         0.00000           NaN
StorageUnit Battery storage                         195.00000  1.613284e+04
            Pumped hydro                          26446.00000  8.547575e+06

                                              Withdrawal Energy Balance  \
                                                    2023           2023
Generator   Biomass                                  NaN   2.794947e+07
            Blue ammonia & coal co-firing            NaN            NaN
            Blue hydrogen & gas co-firing            NaN            NaN
            Coal                                     NaN   3.499852e+08
            Gas                                      NaN   2.179211e+08
            Geothermal                               NaN   1.890777e+06
            Green ammonia & coal co-firing           NaN            NaN
            Green hydrogen & gas co-firing           NaN            NaN
            Hydro conventional                       NaN   6.832994e+07
            Nuclear                                  NaN   7.717479e+07
            Offshore wind                            NaN            NaN
            Oil                                      NaN   3.694876e+03
            Onshore wind                             NaN   9.143532e+06
            Solar grid-scale                         NaN   1.011240e+08
Link        Transmission                    6.178259e+07  -1.853478e+06
Load        -                               8.512181e+08  -8.512181e+08
StorageUnit Battery storage                 1.714617e+04  -1.013339e+03
            Pumped hydro                    8.997447e+06  -4.498723e+05

                                            Transmission Capacity Factor  \
                                                    2023            2023
Generator   Biomass                         0.000000e+00        0.511558
            Blue ammonia & coal co-firing   0.000000e+00             NaN
            Blue hydrogen & gas co-firing   0.000000e+00             NaN
            Coal                            0.000000e+00        0.876308
            Gas                             0.000000e+00        0.338258
            Geothermal                      0.000000e+00        0.471786
            Green ammonia & coal co-firing  0.000000e+00             NaN
            Green hydrogen & gas co-firing  0.000000e+00             NaN
            Hydro conventional              0.000000e+00        0.390073
            Nuclear                         0.000000e+00        0.288566
            Offshore wind                   0.000000e+00             NaN
            Oil                             0.000000e+00        0.000021
            Onshore wind                    0.000000e+00        0.237493
            Solar grid-scale                0.000000e+00        0.175836
Link        Transmission                    6.178259e+07        0.175968
Load        -                               0.000000e+00             NaN
StorageUnit Battery storage                 0.000000e+00        0.019482
            Pumped hydro                    0.000000e+00        0.075734

                                             Curtailment Capital Expenditure  \
                                                    2023                2023
Generator   Biomass                         1.040311e+05                 NaN
            Blue ammonia & coal co-firing            NaN                 NaN
            Blue hydrogen & gas co-firing            NaN                 NaN
            Coal                            4.940074e+07                 NaN
            Gas                             4.263244e+08                 NaN
            Geothermal                      1.382572e+03                 NaN
            Green ammonia & coal co-firing           NaN                 NaN
            Green hydrogen & gas co-firing           NaN                 NaN
            Hydro conventional              1.264040e+04                 NaN
            Nuclear                         5.256019e+05                 NaN
            Offshore wind                            NaN                 NaN
            Oil                             1.734005e+08                 NaN
            Onshore wind                             NaN                 NaN
            Solar grid-scale                6.246991e+03                 NaN
Link        Transmission                    0.000000e+00                 NaN
Load        -                               0.000000e+00                 0.0
StorageUnit Battery storage                 1.709213e+06                 NaN
            Pumped hydro                    2.321168e+08                 NaN

                                           Operational Expenditure  \
                                                              2023
Generator   Biomass                                   7.087985e+08
            Blue ammonia & coal co-firing                      NaN
            Blue hydrogen & gas co-firing                      NaN
            Coal                                      1.434589e+10
            Gas                                       1.925769e+10
            Geothermal                                         NaN
            Green ammonia & coal co-firing                     NaN
            Green hydrogen & gas co-firing                     NaN
            Hydro conventional                                 NaN
            Nuclear                                   9.361302e+08
            Offshore wind                                      NaN
            Oil                                       6.238799e+05
            Onshore wind                                       NaN
            Solar grid-scale                                   NaN
Link        Transmission                                       NaN
Load        -                                         0.000000e+00
StorageUnit Battery storage                                    NaN
            Pumped hydro                                       NaN

                                                 Revenue Market Value
                                                    2023         2023
Generator   Biomass                         2.116144e+09    75.713201
            Blue ammonia & coal co-firing            NaN          NaN
            Blue hydrogen & gas co-firing            NaN          NaN
            Coal                            2.576418e+10    73.615048
            Gas                             1.930477e+10    88.586043
            Geothermal                      1.273357e+08    67.345690
            Green ammonia & coal co-firing           NaN          NaN
            Green hydrogen & gas co-firing           NaN          NaN
            Hydro conventional              4.872942e+09    71.314880
            Nuclear                         4.286233e+09    55.539290
            Offshore wind                            NaN          NaN
            Oil                             6.238799e+05   168.849807
            Onshore wind                    6.780014e+08    74.150930
            Solar grid-scale                7.016465e+09    69.384775
Link        Transmission                    8.264054e+08    13.789716
Load        -                              -6.508907e+10          NaN
StorageUnit Battery storage                 4.908349e+05    30.424554
            Pumped hydro                    9.548281e+07    11.170748

In [6]:
df_hourly = wrangle.transform_visualiser_hourly_output(n)

Please enter the market/country/region for this Pypsa run.
Examples: 'ASEAN, Japan, Taiwan, Indonesia, etc'
You entered: Japan
Please enter the run identifier.
Examples: '1, first-run, run-with-policy-constraint, etc'
You entered: test

In [7]:
df_yearly = wrangle.transform_visualiser_yearly_output(n)

Please enter the market/country/region for this Pypsa run.
Examples: 'ASEAN, Japan, Taiwan, Indonesia, etc'
You entered: Japan
Please enter the run identifier.
Examples: '1, first-run, run-with-policy-constraint, etc'
You entered: Updated-bus-level-grouping

In [18]:
df_hourly.to_csv('JPN_2023_hourly.csv', index=False)
df_yearly.to_csv('JPN_2023_yearly.csv', index=False)

In [24]:
n.statistics()

                                           Optimal Capacity  \
                                                       2023
Generator   Biomass                              6236.98000
            Blue ammonia & coal co-firing               NaN
            Blue hydrogen & gas co-firing               NaN
            Coal                                45592.00000
            Gas                                 73544.00000
            Geothermal                            457.50000
            Green ammonia & coal co-firing              NaN
            Green hydrogen & gas co-firing              NaN
            Hydro conventional                  19996.80000
            Nuclear                             30530.00000
            Offshore wind                               NaN
            Oil                                 19795.00000
            Onshore wind                         4395.00000
            Solar grid-scale                    65650.98182
Link        Transmission                        40080.00000
Load        -                                       0.00000
StorageUnit Battery storage                       195.00000
            Pumped hydro                        26446.00000

                                           Installed Capacity        Supply  \
                                                         2023          2023
Generator   Biomass                                6236.98000  2.794947e+07
            Blue ammonia & coal co-firing                 NaN           NaN
            Blue hydrogen & gas co-firing                 NaN           NaN
            Coal                                  45592.00000  3.499852e+08
            Gas                                   73544.00000  2.179211e+08
            Geothermal                              457.50000  1.890777e+06
            Green ammonia & coal co-firing                NaN           NaN
            Green hydrogen & gas co-firing                NaN           NaN
            Hydro conventional                    19996.80000  6.832994e+07
            Nuclear                               30530.00000  7.717479e+07
            Offshore wind                                 NaN           NaN
            Oil                                   19795.00000  3.694876e+03
            Onshore wind                           4395.00000  9.143532e+06
            Solar grid-scale                      65650.98182  1.011240e+08
Link        Transmission                          40080.00000  5.992911e+07
Load        -                                         0.00000           NaN
StorageUnit Battery storage                         195.00000  1.613284e+04
            Pumped hydro                          26446.00000  8.547575e+06

                                              Withdrawal Energy Balance  \
                                                    2023           2023
Generator   Biomass                                  NaN   2.794947e+07
            Blue ammonia & coal co-firing            NaN            NaN
            Blue hydrogen & gas co-firing            NaN            NaN
            Coal                                     NaN   3.499852e+08
            Gas                                      NaN   2.179211e+08
            Geothermal                               NaN   1.890777e+06
            Green ammonia & coal co-firing           NaN            NaN
            Green hydrogen & gas co-firing           NaN            NaN
            Hydro conventional                       NaN   6.832994e+07
            Nuclear                                  NaN   7.717479e+07
            Offshore wind                            NaN            NaN
            Oil                                      NaN   3.694876e+03
            Onshore wind                             NaN   9.143532e+06
            Solar grid-scale                         NaN   1.011240e+08
Link        Transmission                    6.178259e+07  -1.853478e+06
Load        -                               8.512181e+08  -8.512181e+08
StorageUnit Battery storage                 1.714617e+04  -1.013339e+03
            Pumped hydro                    8.997447e+06  -4.498723e+05

                                            Transmission Capacity Factor  \
                                                    2023            2023
Generator   Biomass                         0.000000e+00        0.511558
            Blue ammonia & coal co-firing   0.000000e+00             NaN
            Blue hydrogen & gas co-firing   0.000000e+00             NaN
            Coal                            0.000000e+00        0.876308
            Gas                             0.000000e+00        0.338258
            Geothermal                      0.000000e+00        0.471786
            Green ammonia & coal co-firing  0.000000e+00             NaN
            Green hydrogen & gas co-firing  0.000000e+00             NaN
            Hydro conventional              0.000000e+00        0.390073
            Nuclear                         0.000000e+00        0.288566
            Offshore wind                   0.000000e+00             NaN
            Oil                             0.000000e+00        0.000021
            Onshore wind                    0.000000e+00        0.237493
            Solar grid-scale                0.000000e+00        0.175836
Link        Transmission                    6.178259e+07        0.175968
Load        -                               0.000000e+00             NaN
StorageUnit Battery storage                 0.000000e+00        0.019482
            Pumped hydro                    0.000000e+00        0.075734

                                             Curtailment Capital Expenditure  \
                                                    2023                2023
Generator   Biomass                         1.040311e+05                 NaN
            Blue ammonia & coal co-firing            NaN                 NaN
            Blue hydrogen & gas co-firing            NaN                 NaN
            Coal                            4.940074e+07                 NaN
            Gas                             4.263244e+08                 NaN
            Geothermal                      1.382572e+03                 NaN
            Green ammonia & coal co-firing           NaN                 NaN
            Green hydrogen & gas co-firing           NaN                 NaN
            Hydro conventional              1.264040e+04                 NaN
            Nuclear                         5.256019e+05                 NaN
            Offshore wind                            NaN                 NaN
            Oil                             1.734005e+08                 NaN
            Onshore wind                             NaN                 NaN
            Solar grid-scale                6.246991e+03                 NaN
Link        Transmission                    0.000000e+00                 NaN
Load        -                               0.000000e+00                 0.0
StorageUnit Battery storage                 1.709213e+06                 NaN
            Pumped hydro                    2.321168e+08                 NaN

                                           Operational Expenditure  \
                                                              2023
Generator   Biomass                                   7.087985e+08
            Blue ammonia & coal co-firing                      NaN
            Blue hydrogen & gas co-firing                      NaN
            Coal                                      1.434589e+10
            Gas                                       1.925769e+10
            Geothermal                                         NaN
            Green ammonia & coal co-firing                     NaN
            Green hydrogen & gas co-firing                     NaN
            Hydro conventional                                 NaN
            Nuclear                                   9.361302e+08
            Offshore wind                                      NaN
            Oil                                       6.238799e+05
            Onshore wind                                       NaN
            Solar grid-scale                                   NaN
Link        Transmission                                       NaN
Load        -                                         0.000000e+00
StorageUnit Battery storage                                    NaN
            Pumped hydro                                       NaN

                                                 Revenue Market Value
                                                    2023         2023
Generator   Biomass                         2.116144e+09    75.713201
            Blue ammonia & coal co-firing            NaN          NaN
            Blue hydrogen & gas co-firing            NaN          NaN
            Coal                            2.576418e+10    73.615048
            Gas                             1.930477e+10    88.586043
            Geothermal                      1.273357e+08    67.345690
            Green ammonia & coal co-firing           NaN          NaN
            Green hydrogen & gas co-firing           NaN          NaN
            Hydro conventional              4.872942e+09    71.314880
            Nuclear                         4.286233e+09    55.539290
            Offshore wind                            NaN          NaN
            Oil                             6.238799e+05   168.849807
            Onshore wind                    6.780014e+08    74.150930
            Solar grid-scale                7.016465e+09    69.384775
Link        Transmission                    8.264054e+08    13.789716
Load        -                              -6.508907e+10          NaN
StorageUnit Battery storage                 4.908349e+05    30.424554
            Pumped hydro                    9.548281e+07    11.170748