In [1]:
import matplotlib.pyplot as plt
import numpy as np
import xarray as xr
import pypsa
import xlsxwriter
import tz_pypsa
import tz_pypsa.wrangle as wrangle
import pandas as pd
from tz_pypsa.model import Model
import os
import glob
from pathlib import Path
import gc
from tz_pypsa.wrangle import get_ci_cost_summary

In [7]:
def process_and_save_networks_by_directory(
        base_path: str,
        output_base_path: str,
        pattern: str = "JPN_P1_JPN*",
        network_dir: str = "solved_networks",
        pypsa_run_id: str = 'Unspecified'
    ) -> None:
    """
    Process all .nc files in each solved_networks directory one at a time and
    save results to CSV immediately after processing each directory.

    Parameters
    ----------
    base_path : str
        Base directory path containing the run folders
    output_base_path : str
        Base path where to save the output CSV files
    pattern : str, optional
        Pattern to match subdirectories, defaults to "JPN_P1_JPN*"
    network_dir : str, optional
        Name of directory containing network files, defaults to "solved_networks"
    """

    # Create output directories
    yearly_path = os.path.join(output_base_path, "yearly")
    os.makedirs(yearly_path, exist_ok=True)

    unit_cost_dfs = []
    # Process each directory one at a time
    for dir_path in glob.glob(os.path.join(base_path, pattern)):
        dir_name = os.path.basename(dir_path)
        network_path = os.path.join(dir_path, network_dir)
        
        if not os.path.exists(network_path):
            print(f"Skipping {dir_name}: {network_dir} directory not found")
            continue
            
        # Find all .nc files in the solved_networks directory
        nc_files = glob.glob(os.path.join(network_path, "*.nc"))
        
        if not nc_files:
            print(f"No .nc files found in {network_path}")
            continue
            
        print(f"Processing {len(nc_files)} files in {dir_name}")
        
        # Process each .nc file and collect DataFrames
        yearly_dfs = []
        
        for nc_file in nc_files:
            try:
                # Load network
                network = pypsa.Network()
                network.import_from_netcdf(nc_file)
                
                # Get filename without extension for run_id
                scenario_id = Path(nc_file).stem
                
                yearly_df = wrangle.get_ci_unit_cost(
                    n=network
                )
                yearly_df['scenario_id'] = scenario_id
                yearly_df['pypsa_run_id'] = pypsa_run_id

                yearly_dfs.append(yearly_df)
                
                # Clean up to free memory
                del network
                gc.collect()
                
            except Exception as e:
                print(f"Error processing {nc_file}: {str(e)}")
                continue
        
        if yearly_dfs:
            yearly_output = pd.concat(yearly_dfs, ignore_index=True)
            print(f"Successfully processed and saved results for {dir_name}")
        else:
            print(f"No valid data processed for {dir_name}")

        unit_cost_dfs.append(yearly_output)

    unit_cost_output = pd.concat(unit_cost_dfs, ignore_index=True)
    unit_cost_output.to_csv(os.path.join(yearly_path, f"{pypsa_run_id}_unit_costs.csv"), index=False)

In [9]:
base_path = "C:/Users/jy/TransitionZero/Google - CFE - Documents/04. Country Specific Vault/Japan/02. Data & Results/Outputs/1_Diagnosis/TP3/Run009"
output_path = "C:/Users/jy/Projects/tza-pypsa/csv_outputs"

process_and_save_networks_by_directory(
    base_path=base_path,
    output_base_path=output_path,
    pattern="JPN_P3_JPN0*_009",
    network_dir="solved_networks",
    pypsa_run_id="JPN_P3_009"
)

Processing 8 files in JPN_P3_JPN01_009

INFO:pypsa.io:Imported network annual_matching_RES100_2030.nc has buses, carriers, generators, links, loads, storage_units
INFO:pypsa.io:Imported network brownfield_2030.nc has buses, carriers, generators, links, loads, storage_units
INFO:pypsa.io:Imported network hourly_matching_CFE100_2030.nc has buses, carriers, generators, links, loads, storage_units
INFO:pypsa.io:Imported network hourly_matching_CFE70_2030.nc has buses, carriers, generators, links, loads, storage_units
INFO:pypsa.io:Imported network hourly_matching_CFE80_2030.nc has buses, carriers, generators, links, loads, storage_units
INFO:pypsa.io:Imported network hourly_matching_CFE90_2030.nc has buses, carriers, generators, links, loads, storage_units
INFO:pypsa.io:Imported network hourly_matching_CFE95_2030.nc has buses, carriers, generators, links, loads, storage_units
INFO:pypsa.io:Imported network hourly_matching_CFE99_2030.nc has buses, carriers, generators, links, loads, storage_units

Successfully processed and saved results for JPN_P3_JPN01_009
Processing 8 files in JPN_P3_JPN02_009

INFO:pypsa.io:Imported network annual_matching_RES100_2030.nc has buses, carriers, generators, links, loads, storage_units
INFO:pypsa.io:Imported network brownfield_2030.nc has buses, carriers, generators, links, loads, storage_units
INFO:pypsa.io:Imported network hourly_matching_CFE100_2030.nc has buses, carriers, generators, links, loads, storage_units
INFO:pypsa.io:Imported network hourly_matching_CFE70_2030.nc has buses, carriers, generators, links, loads, storage_units
INFO:pypsa.io:Imported network hourly_matching_CFE80_2030.nc has buses, carriers, generators, links, loads, storage_units
INFO:pypsa.io:Imported network hourly_matching_CFE90_2030.nc has buses, carriers, generators, links, loads, storage_units
INFO:pypsa.io:Imported network hourly_matching_CFE95_2030.nc has buses, carriers, generators, links, loads, storage_units
INFO:pypsa.io:Imported network hourly_matching_CFE99_2030.nc has buses, carriers, generators, links, loads, storage_units

Successfully processed and saved results for JPN_P3_JPN02_009
Processing 8 files in JPN_P3_JPN03_009

INFO:pypsa.io:Imported network annual_matching_RES100_2030.nc has buses, carriers, generators, links, loads, storage_units
INFO:pypsa.io:Imported network brownfield_2030.nc has buses, carriers, generators, links, loads, storage_units
INFO:pypsa.io:Imported network hourly_matching_CFE100_2030.nc has buses, carriers, generators, links, loads, storage_units
INFO:pypsa.io:Imported network hourly_matching_CFE70_2030.nc has buses, carriers, generators, links, loads, storage_units
INFO:pypsa.io:Imported network hourly_matching_CFE80_2030.nc has buses, carriers, generators, links, loads, storage_units
INFO:pypsa.io:Imported network hourly_matching_CFE90_2030.nc has buses, carriers, generators, links, loads, storage_units
INFO:pypsa.io:Imported network hourly_matching_CFE95_2030.nc has buses, carriers, generators, links, loads, storage_units
INFO:pypsa.io:Imported network hourly_matching_CFE99_2030.nc has buses, carriers, generators, links, loads, storage_units

Successfully processed and saved results for JPN_P3_JPN03_009
Processing 8 files in JPN_P3_JPN04_009

INFO:pypsa.io:Imported network annual_matching_RES100_2030.nc has buses, carriers, generators, links, loads, storage_units
INFO:pypsa.io:Imported network brownfield_2030.nc has buses, carriers, generators, links, loads, storage_units
INFO:pypsa.io:Imported network hourly_matching_CFE100_2030.nc has buses, carriers, generators, links, loads, storage_units
INFO:pypsa.io:Imported network hourly_matching_CFE70_2030.nc has buses, carriers, generators, links, loads, storage_units
INFO:pypsa.io:Imported network hourly_matching_CFE80_2030.nc has buses, carriers, generators, links, loads, storage_units
INFO:pypsa.io:Imported network hourly_matching_CFE90_2030.nc has buses, carriers, generators, links, loads, storage_units
INFO:pypsa.io:Imported network hourly_matching_CFE95_2030.nc has buses, carriers, generators, links, loads, storage_units
INFO:pypsa.io:Imported network hourly_matching_CFE99_2030.nc has buses, carriers, generators, links, loads, storage_units

Successfully processed and saved results for JPN_P3_JPN04_009
Processing 8 files in JPN_P3_JPN05_009

INFO:pypsa.io:Imported network annual_matching_RES100_2030.nc has buses, carriers, generators, links, loads, storage_units
INFO:pypsa.io:Imported network brownfield_2030.nc has buses, carriers, generators, links, loads, storage_units
INFO:pypsa.io:Imported network hourly_matching_CFE100_2030.nc has buses, carriers, generators, links, loads, storage_units
INFO:pypsa.io:Imported network hourly_matching_CFE70_2030.nc has buses, carriers, generators, links, loads, storage_units
INFO:pypsa.io:Imported network hourly_matching_CFE80_2030.nc has buses, carriers, generators, links, loads, storage_units
INFO:pypsa.io:Imported network hourly_matching_CFE90_2030.nc has buses, carriers, generators, links, loads, storage_units
INFO:pypsa.io:Imported network hourly_matching_CFE95_2030.nc has buses, carriers, generators, links, loads, storage_units
INFO:pypsa.io:Imported network hourly_matching_CFE99_2030.nc has buses, carriers, generators, links, loads, storage_units

Successfully processed and saved results for JPN_P3_JPN05_009
Processing 8 files in JPN_P3_JPN06_009

INFO:pypsa.io:Imported network annual_matching_RES100_2030.nc has buses, carriers, generators, links, loads, storage_units
INFO:pypsa.io:Imported network brownfield_2030.nc has buses, carriers, generators, links, loads, storage_units
INFO:pypsa.io:Imported network hourly_matching_CFE100_2030.nc has buses, carriers, generators, links, loads, storage_units
INFO:pypsa.io:Imported network hourly_matching_CFE70_2030.nc has buses, carriers, generators, links, loads, storage_units
INFO:pypsa.io:Imported network hourly_matching_CFE80_2030.nc has buses, carriers, generators, links, loads, storage_units
INFO:pypsa.io:Imported network hourly_matching_CFE90_2030.nc has buses, carriers, generators, links, loads, storage_units
INFO:pypsa.io:Imported network hourly_matching_CFE95_2030.nc has buses, carriers, generators, links, loads, storage_units
INFO:pypsa.io:Imported network hourly_matching_CFE99_2030.nc has buses, carriers, generators, links, loads, storage_units

Successfully processed and saved results for JPN_P3_JPN06_009
Processing 8 files in JPN_P3_JPN07_009

INFO:pypsa.io:Imported network annual_matching_RES100_2030.nc has buses, carriers, generators, links, loads, storage_units
INFO:pypsa.io:Imported network brownfield_2030.nc has buses, carriers, generators, links, loads, storage_units
INFO:pypsa.io:Imported network hourly_matching_CFE100_2030.nc has buses, carriers, generators, links, loads, storage_units
INFO:pypsa.io:Imported network hourly_matching_CFE70_2030.nc has buses, carriers, generators, links, loads, storage_units
INFO:pypsa.io:Imported network hourly_matching_CFE80_2030.nc has buses, carriers, generators, links, loads, storage_units
INFO:pypsa.io:Imported network hourly_matching_CFE90_2030.nc has buses, carriers, generators, links, loads, storage_units
INFO:pypsa.io:Imported network hourly_matching_CFE95_2030.nc has buses, carriers, generators, links, loads, storage_units
INFO:pypsa.io:Imported network hourly_matching_CFE99_2030.nc has buses, carriers, generators, links, loads, storage_units

Successfully processed and saved results for JPN_P3_JPN07_009
Processing 8 files in JPN_P3_JPN08_009

INFO:pypsa.io:Imported network annual_matching_RES100_2030.nc has buses, carriers, generators, links, loads, storage_units
INFO:pypsa.io:Imported network brownfield_2030.nc has buses, carriers, generators, links, loads, storage_units
INFO:pypsa.io:Imported network hourly_matching_CFE100_2030.nc has buses, carriers, generators, links, loads, storage_units
INFO:pypsa.io:Imported network hourly_matching_CFE70_2030.nc has buses, carriers, generators, links, loads, storage_units
INFO:pypsa.io:Imported network hourly_matching_CFE80_2030.nc has buses, carriers, generators, links, loads, storage_units
INFO:pypsa.io:Imported network hourly_matching_CFE90_2030.nc has buses, carriers, generators, links, loads, storage_units
INFO:pypsa.io:Imported network hourly_matching_CFE95_2030.nc has buses, carriers, generators, links, loads, storage_units
INFO:pypsa.io:Imported network hourly_matching_CFE99_2030.nc has buses, carriers, generators, links, loads, storage_units

Successfully processed and saved results for JPN_P3_JPN08_009
Processing 8 files in JPN_P3_JPN09_009

INFO:pypsa.io:Imported network annual_matching_RES100_2030.nc has buses, carriers, generators, links, loads, storage_units
INFO:pypsa.io:Imported network brownfield_2030.nc has buses, carriers, generators, links, loads, storage_units
INFO:pypsa.io:Imported network hourly_matching_CFE100_2030.nc has buses, carriers, generators, links, loads, storage_units
INFO:pypsa.io:Imported network hourly_matching_CFE70_2030.nc has buses, carriers, generators, links, loads, storage_units
INFO:pypsa.io:Imported network hourly_matching_CFE80_2030.nc has buses, carriers, generators, links, loads, storage_units
INFO:pypsa.io:Imported network hourly_matching_CFE90_2030.nc has buses, carriers, generators, links, loads, storage_units
INFO:pypsa.io:Imported network hourly_matching_CFE95_2030.nc has buses, carriers, generators, links, loads, storage_units
INFO:pypsa.io:Imported network hourly_matching_CFE99_2030.nc has buses, carriers, generators, links, loads, storage_units

Successfully processed and saved results for JPN_P3_JPN09_009

In [5]:
wrangle.get_ci_unit_cost(n)

,index,carrier,p_nom,p_nom_opt,capital_cost,marginal_cost,p_max_pu,dispatch,potential_dispatch,curtailment,...,ci_load,grid_exports,grid_imports,ppa_weighting,import_weighting,import_unit_cost,ppa_unit_cost,export_unit_cost,unit_cost_all_energy,unit_cost_ci_energy
0,JPN03 C&I Grid-solar-unspecified-ext-2030-PPA-...,SolarGrid,0.000,2296.999,116365.000,0.00,1.0,3288659.753,3288660.076,0.323,...,9785312.812,2599289.863,0.006,1.0,6.131638e-10,0.000000e+00,21.582468,0.000000,2.158247e+01,2.731546e+01
1,JPN03 C&I Grid-onshorewind-unspecified-ext-203...,OnshoreWind,0.000,301.000,221368.000,0.00,1.0,618911.120,618911.431,0.311,...,9785312.812,2599289.863,0.006,1.0,6.131638e-10,0.000000e+00,5.380210,0.000000,5.380210e+00,6.809365e+00
2,JPN03 C&I Grid-gas-CCS-unspecified-ext-2030-PP...,GasCCSLeaked,0.000,460.953,295309.000,69.44,1.0,2583699.124,4037950.919,1454251.795,...,9785312.812,2599289.863,0.006,1.0,6.131638e-10,0.000000e+00,25.478059,0.000000,2.280070e+01,3.224584e+01
3,JPN03 C&I Grid-gas-CCS-unspecified-ext-2030-PP...,GasCCSSequestered,0.000,1075.558,295309.000,96.13,1.0,6028631.289,9421884.459,3393253.170,...,9785312.812,2599289.863,0.006,1.0,6.131638e-10,0.000000e+00,72.441103,0.000000,5.686161e+01,9.168376e+01
4,JPN03 C&I Grid-Batteries,Batteries,0.000,130.080,196741.449,0.00,0.0,0.000,0.000,0.000,...,9785312.812,2599289.863,0.006,1.0,6.131638e-10,0.000000e+00,2.066447,0.000000,2.066447e+00,2.615361e+00
5,JPN03 C&I Grid-LAES,LAES,0.000,642.502,368432.767,0.00,0.0,0.000,0.000,0.000,...,9785312.812,2599289.863,0.006,1.0,6.131638e-10,0.000000e+00,19.113959,0.000000,1.911396e+01,2.419123e+01
6,JPN03 C&I Grid Imports,Grid Imports,1995.625,3647.058,0.000,0.00,0.0,0.006,0.000,0.000,...,9785312.812,2599289.863,0.006,1.0,6.131638e-10,3.784967e-08,0.000000,0.000000,2.990575e-08,3.784967e-08
7,JPN03 C&I Grid Exports,Grid Exports,0.000,2691.869,0.000,0.00,0.0,2599289.863,0.000,0.000,...,9785312.812,2599289.863,0.006,1.0,6.131638e-10,0.000000e+00,0.000000,-13.285254,-1.328525e+01,-1.681424e+01

In [5]:
hourly_df = wrangle.transform_visualiser_hourly_output(n)

In [12]:
n.storage_units_t.p[n.storage_units[n.storage_units.p_nom_opt > 1e-2].index].reset_index()

StorageUnit,snapshot,JPN01-PumpedHydro-2023active_exo,JPN01-Batteries-2023active_exo,JPN01-Batteries-2030_exo,JPN02-PumpedHydro-2023active_exo,JPN02-Batteries-2023active_exo,JPN02-Batteries-2030_exo,JPN03-PumpedHydro-2023active_exo,JPN03-Batteries-2023active_exo,JPN03-Batteries-2030_exo,...,JPN06-Batteries-2030_exo,JPN07-PumpedHydro-2023active_exo,JPN07-Batteries-2023active_exo,JPN07-Batteries-2030_exo,JPN08-PumpedHydro-2023active_exo,JPN09-PumpedHydro-2023active_exo,JPN09-Batteries-2023active_exo,JPN09-Batteries-2030_exo,JPN03 C&I Grid-Batteries,JPN03 C&I Grid-LAES
0,2030-01-01 00:00:00,-0.006569,-0.006488,-0.008598,-0.005565,-0.006214,-0.007439,-0.059629,-0.239476,-1.358110,...,-0.008688,-0.008500,-0.007831,-0.008766,-0.007343,-0.007354,-0.007759,-0.009250,-2.655823,-6.802522
1,2030-01-01 01:00:00,-0.002807,-0.002333,-0.003223,-0.002270,-0.002171,-0.002670,-0.037645,-0.099060,-0.641815,...,-0.003475,-0.003948,-0.002902,-0.003529,-0.003204,-0.003145,-0.002915,-0.003572,-2.914834,-24.057166
2,2030-01-01 02:00:00,-0.001961,-0.001195,-0.001990,-0.001384,-0.001001,-0.001288,-0.030271,-0.075986,-0.487802,...,-0.002031,-0.002687,-0.001641,-0.002056,-0.002099,-0.002082,-0.001661,-0.002185,-2.981785,-31.237316
3,2030-01-01 03:00:00,-0.001177,-0.000293,-0.000635,-0.000885,-0.000253,-0.000402,-0.025847,-0.064907,-0.413251,...,-0.001202,-0.001947,-0.000932,-0.001209,-0.001507,-0.001280,-0.000901,-0.001306,-3.037030,-36.233764
4,2030-01-01 04:00:00,-0.000649,0.000429,0.000454,-0.000517,0.000430,0.000418,-0.023021,-0.057750,-0.367163,...,-0.000578,-0.001413,-0.000403,-0.000574,-0.001096,-0.000683,-0.000332,-0.000667,-3.138640,-38.223971
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,2030-12-31 19:00:00,0.001397,0.001435,0.001455,0.002034,0.002323,0.002462,0.024086,0.026583,0.051195,...,40.137666,41.534906,0.902922,38.436248,15.763083,50.859257,8.190030,234.952241,-2.608688,-5.708082
8756,2030-12-31 20:00:00,0.001774,0.001993,0.002055,0.002487,0.002923,0.003103,0.026300,0.030440,0.058116,...,44.570265,46.836695,0.932965,42.536488,17.678478,57.129035,8.369744,248.381190,-2.842212,-10.861314
8757,2030-12-31 21:00:00,0.002409,0.002819,0.002966,0.003235,0.003843,0.004106,0.029692,0.036396,0.069143,...,51.577117,54.534194,1.016847,49.125110,20.970188,66.171653,9.022024,262.554898,-2.816061,-18.229635
8758,2030-12-31 22:00:00,0.003932,0.004367,0.004887,0.004724,0.005620,0.006294,0.036159,0.048258,0.091755,...,65.901588,68.741634,1.226361,62.718797,28.725638,85.842835,10.738639,298.720133,-2.812428,-25.159565
8759,2030-12-31 23:00:00,0.013467,0.010541,0.016390,0.013373,0.012846,0.018360,0.060030,0.106983,0.212289,...,160.054411,185.214799,2.102642,145.217791,83.927527,204.841256,17.938735,386.840287,-2.860345,-27.416300

In [24]:
storage_lookup = (n
                    .storage_units
                    .reset_index()[['StorageUnit', 'bus', 'carrier']]
                    .rename(
                        columns={'bus': 'Node', 'carrier': 'Tech'})
                    )

In [26]:
n.storage_units.carrier.unique()

array(['PumpedHydro', 'Batteries', 'LAES'], dtype=object)

In [35]:
n.statistics.optimal_capacity(groupby='carrier', nice_names=False)

component    carrier
StorageUnit  Batteries             4414.65285
             LAES                   642.50353
             PumpedHydro          26444.33000
Generator    Biomass              22567.92058
             BlueH2                 120.00022
             BlueH2_Gas            1080.00027
             BlueNH3                920.00050
             BlueNH3_Coal          2180.00052
             Coal                 42491.73000
             Gas                  79318.97255
             GasCCSLeaked           535.95427
             GasCCSSequestered     1250.55860
             Geothermal             583.07225
             HydroConventional    21122.13000
             Nuclear              20733.00000
             OffshoreWind          3364.00000
             Oil                  19795.38000
             OnshoreWind           7636.43474
             SolarGrid            82818.21788
Link         AC                   11458.95161
             Transmission         48380.00000
dtype: float64

In [28]:
n.carriers

,co2_emissions,color,nice_name,max_growth,max_relative_growth
Carrier,,,,,
Coal,0.3600,#322f34,Coal,inf,0.0
Gas,0.1980,#bababa,Gas,inf,0.0
Oil,0.2571,#5d407c,Oil,inf,0.0
GasCCSLeaked,0.1980,#d9d9d9,Gas CCS: Leaked Component,inf,0.0
BlueNH3,0.0000,#d9a88b,Coal & blue NH3: NH3,inf,0.0
BlueH2,0.0000,#f3f3f3,Gas & blue H2: H2,inf,0.0
GreenNH3,0.0000,#d9a88b,Coal & green NH3: NH3,inf,0.0
GreenH2,0.0000,#f3f3f3,Gas & green H2: H2,inf,0.0
Nuclear,0.0000,#ee9dda,Nuclear,inf,0.0
Biomass,0.0000,#e25329,Biomass,inf,0.0
Geothermal,0.0000,#f75726,Geothermal,inf,0.0
HydroConventional,0.0000,#8292e8,Hydro conventional,inf,0.0
SolarGrid,0.0000,#ffe19b,Solar,inf,0.0
OffshoreWind,0.0000,#66dad0,Offshore Wind,inf,0.0
OnshoreWind,0.0000,#99e6df,Onshore Wind,inf,0.0
PumpedHydro,0.0000,#a5d1f9,Pumped hydro,inf,0.0
Batteries,0.0000,#c3e0fb,Batteries,inf,0.0
Transmission,0.0000,#ba63da,Transmission,inf,0.0
GasCCSSequestered,0.0000,#d9d9d9,Gas CCS: Sequestered component,inf,0.0
BlueNH3_Coal,0.3600,#322f34,Coal & blue NH3: Coal,inf,0.0
BlueH2_Gas,0.1980,#bababa,Gas & blue H2: Gas,inf,0.0
GreenNH3_Coal,0.3600,#322f34,Coal & green NH3: Coal,inf,0.0
GreenH2_Gas,0.1980,#bababa,Gas & green H2: Gas,inf,0.0
AC,0.0000,#ba63da,Transmission,inf,0.0
LAES,0.0000,#c3e0fb,Liquid Air Energy Storage,inf,0.0

In [25]:
storage_lookup

                         StorageUnit               Node         Tech
0   JPN01-PumpedHydro-2023active_exo              JPN01  PumpedHydro
1         JPN01-PumpedHydro-2030_exo              JPN01  PumpedHydro
2     JPN01-Batteries-2023active_exo              JPN01    Batteries
3          JPN01-Batteries-2030_endo              JPN01    Batteries
4           JPN01-Batteries-2030_exo              JPN01    Batteries
5   JPN02-PumpedHydro-2023active_exo              JPN02  PumpedHydro
6         JPN02-PumpedHydro-2030_exo              JPN02  PumpedHydro
7     JPN02-Batteries-2023active_exo              JPN02    Batteries
8          JPN02-Batteries-2030_endo              JPN02    Batteries
9           JPN02-Batteries-2030_exo              JPN02    Batteries
10  JPN03-PumpedHydro-2023active_exo              JPN03  PumpedHydro
11        JPN03-PumpedHydro-2030_exo              JPN03  PumpedHydro
12    JPN03-Batteries-2023active_exo              JPN03    Batteries
13         JPN03-Batteries-2030_endo              JPN03    Batteries
14          JPN03-Batteries-2030_exo              JPN03    Batteries
15  JPN04-PumpedHydro-2023active_exo              JPN04  PumpedHydro
16        JPN04-PumpedHydro-2030_exo              JPN04  PumpedHydro
17    JPN04-Batteries-2023active_exo              JPN04    Batteries
18         JPN04-Batteries-2030_endo              JPN04    Batteries
19          JPN04-Batteries-2030_exo              JPN04    Batteries
20  JPN05-PumpedHydro-2023active_exo              JPN05  PumpedHydro
21        JPN05-PumpedHydro-2030_exo              JPN05  PumpedHydro
22    JPN05-Batteries-2023active_exo              JPN05    Batteries
23         JPN05-Batteries-2030_endo              JPN05    Batteries
24          JPN05-Batteries-2030_exo              JPN05    Batteries
25  JPN06-PumpedHydro-2023active_exo              JPN06  PumpedHydro
26        JPN06-PumpedHydro-2030_exo              JPN06  PumpedHydro
27    JPN06-Batteries-2023active_exo              JPN06    Batteries
28         JPN06-Batteries-2030_endo              JPN06    Batteries
29          JPN06-Batteries-2030_exo              JPN06    Batteries
30  JPN07-PumpedHydro-2023active_exo              JPN07  PumpedHydro
31        JPN07-PumpedHydro-2030_exo              JPN07  PumpedHydro
32    JPN07-Batteries-2023active_exo              JPN07    Batteries
33         JPN07-Batteries-2030_endo              JPN07    Batteries
34          JPN07-Batteries-2030_exo              JPN07    Batteries
35  JPN08-PumpedHydro-2023active_exo              JPN08  PumpedHydro
36        JPN08-PumpedHydro-2030_exo              JPN08  PumpedHydro
37    JPN08-Batteries-2023active_exo              JPN08    Batteries
38         JPN08-Batteries-2030_endo              JPN08    Batteries
39          JPN08-Batteries-2030_exo              JPN08    Batteries
40  JPN09-PumpedHydro-2023active_exo              JPN09  PumpedHydro
41        JPN09-PumpedHydro-2030_exo              JPN09  PumpedHydro
42    JPN09-Batteries-2023active_exo              JPN09    Batteries
43         JPN09-Batteries-2030_endo              JPN09    Batteries
44          JPN09-Batteries-2030_exo              JPN09    Batteries
45              JPN01-LAES-2030_endo              JPN01         LAES
46              JPN02-LAES-2030_endo              JPN02         LAES
47              JPN03-LAES-2030_endo              JPN03         LAES
48              JPN04-LAES-2030_endo              JPN04         LAES
49              JPN05-LAES-2030_endo              JPN05         LAES
50              JPN06-LAES-2030_endo              JPN06         LAES
51              JPN07-LAES-2030_endo              JPN07         LAES
52              JPN08-LAES-2030_endo              JPN08         LAES
53              JPN09-LAES-2030_endo              JPN09         LAES
54          JPN03 C&I Grid-Batteries  JPN03 C&I Storage    Batteries
55               JPN03 C&I Grid-LAES  JPN03 C&I Storage         LAES

In [22]:
optimal_capacity = (
    n
    .statistics
    .optimal_capacity(groupby=['bus', 'carrier'])
    .reset_index()
    .rename(columns={'bus':'Node', 'carrier': 'Tech',  0: 'OptimalCapacity'})
    .drop(columns='component')
)

In [23]:
optimal_capacity.head(50)

                 Node                            Tech  OptimalCapacity
0               JPN01                       Batteries       1356.46030
1               JPN01       Liquid Air Energy Storage          0.00015
2               JPN01                    Pumped hydro        807.17000
3               JPN02                       Batteries        854.39030
4               JPN02       Liquid Air Energy Storage          0.00015
5               JPN02                    Pumped hydro        278.57000
6               JPN03                       Batteries          7.00032
7               JPN03       Liquid Air Energy Storage          0.00015
8               JPN03                    Pumped hydro      11524.75000
9   JPN03 C&I Storage                       Batteries        130.07975
10  JPN03 C&I Storage       Liquid Air Energy Storage        642.50222
11              JPN04                       Batteries        552.84032
12              JPN04       Liquid Air Energy Storage          0.00015
13              JPN04                    Pumped hydro       4235.70000
14              JPN05                       Batteries        133.36045
15              JPN05       Liquid Air Energy Storage          0.00015
16              JPN05                    Pumped hydro        176.12000
17              JPN06                       Batteries        444.03031
18              JPN06       Liquid Air Energy Storage          0.00015
19              JPN06                    Pumped hydro       4359.38000
20              JPN07                       Batteries        345.51031
21              JPN07       Liquid Air Energy Storage          0.00015
22              JPN07                    Pumped hydro       2095.56000
23              JPN08                       Batteries          0.00045
24              JPN08       Liquid Air Energy Storage          0.00015
25              JPN08                    Pumped hydro        686.57000
26              JPN09                       Batteries        590.98034
27              JPN09       Liquid Air Energy Storage          0.00015
28              JPN09                    Pumped hydro       2280.51000
29              JPN01                         Biomass        779.39006
30              JPN01                            Coal       1929.81000
31              JPN01           Coal & blue NH3: Coal        560.00017
32              JPN01            Coal & blue NH3: NH3        140.00018
33              JPN01                             Gas        991.71026
34              JPN01       Gas CCS: Leaked Component         75.00011
35              JPN01  Gas CCS: Sequestered component        175.00011
36              JPN01                      Geothermal         44.85057
37              JPN01              Hydro conventional       1396.41000
38              JPN01                         Nuclear        912.00000
39              JPN01                   Offshore Wind        112.00000
40              JPN01                             Oil       2083.02000
41              JPN01                    Onshore Wind       1833.11481
42              JPN01                           Solar       2632.14190
43              JPN02                         Biomass       1748.80006
44              JPN02                            Coal       4864.29000
45              JPN02                             Gas       5752.08028
46              JPN02       Gas CCS: Leaked Component          0.00011
47              JPN02  Gas CCS: Sequestered component          0.00011
48              JPN02                      Geothermal        138.70067
49              JPN02              Hydro conventional       2144.50000

In [16]:
n.statistics.optimal_capacity(groupby=['bus', 'type']).reset_index().head(50)

,component,bus,type,0
0,StorageUnit,JPN01,Batteries,1356.46030
1,StorageUnit,JPN01,LiquidAirEnergyStorage,0.00015
2,StorageUnit,JPN01,PumpedHydro,807.17000
3,StorageUnit,JPN02,Batteries,854.39030
4,StorageUnit,JPN02,LiquidAirEnergyStorage,0.00015
5,StorageUnit,JPN02,PumpedHydro,278.57000
6,StorageUnit,JPN03,Batteries,7.00032
7,StorageUnit,JPN03,LiquidAirEnergyStorage,0.00015
8,StorageUnit,JPN03,PumpedHydro,11524.75000
9,StorageUnit,JPN03 C&I Storage,,772.58197
10,StorageUnit,JPN04,Batteries,552.84032
11,StorageUnit,JPN04,LiquidAirEnergyStorage,0.00015
12,StorageUnit,JPN04,PumpedHydro,4235.70000
13,StorageUnit,JPN05,Batteries,133.36045
14,StorageUnit,JPN05,LiquidAirEnergyStorage,0.00015
15,StorageUnit,JPN05,PumpedHydro,176.12000
16,StorageUnit,JPN06,Batteries,444.03031
17,StorageUnit,JPN06,LiquidAirEnergyStorage,0.00015
18,StorageUnit,JPN06,PumpedHydro,4359.38000
19,StorageUnit,JPN07,Batteries,345.51031
20,StorageUnit,JPN07,LiquidAirEnergyStorage,0.00015
21,StorageUnit,JPN07,PumpedHydro,2095.56000
22,StorageUnit,JPN08,Batteries,0.00045
23,StorageUnit,JPN08,LiquidAirEnergyStorage,0.00015
24,StorageUnit,JPN08,PumpedHydro,686.57000
25,StorageUnit,JPN09,Batteries,590.98034
26,StorageUnit,JPN09,LiquidAirEnergyStorage,0.00015
27,StorageUnit,JPN09,PumpedHydro,2280.51000
28,Generator,JPN01,biomass-unspecified,779.39006
29,Generator,JPN01,blending-blueNH3-coal-unspecified,700.00035
30,Generator,JPN01,coal-unspecified,1929.81000
31,Generator,JPN01,gas-CCS-unspecified,250.00022
32,Generator,JPN01,gas-unspecified,991.71026
33,Generator,JPN01,geothermal-unspecified,44.85057
34,Generator,JPN01,hydro-unspecified,1396.41000
35,Generator,JPN01,nuclear-unspecified,912.00000
36,Generator,JPN01,offshorewind-unspecified,112.00000
37,Generator,JPN01,oil-unspecified,2083.02000
38,Generator,JPN01,onshorewind-unspecified,1833.11481
39,Generator,JPN01,solar-unspecified,2632.14190
40,Generator,JPN02,biomass-unspecified,1748.80006
41,Generator,JPN02,coal-unspecified,4864.29000
42,Generator,JPN02,gas-CCS-unspecified,0.00022
43,Generator,JPN02,gas-unspecified,5752.08028
44,Generator,JPN02,geothermal-unspecified,138.70067
45,Generator,JPN02,hydro-unspecified,2144.50000
46,Generator,JPN02,nuclear-unspecified,2208.00000
47,Generator,JPN02,offshorewind-unspecified,1992.00000
48,Generator,JPN02,oil-unspecified,514.29000
49,Generator,JPN02,onshorewind-unspecified,2688.02903

In [18]:
n.storage_units.carrier.unique()

array(['PumpedHydro', 'Batteries', 'LAES'], dtype=object)