In [1]:
import sys
sys.path.insert(0, '/home/jy/tza-pypsa')

# Now your imports will use the local version
import pypsa
from tz_pypsa.constraints import (
    constr_max_annual_utilisation_generator, 
    constr_min_annual_utilisation_generator,
    constr_max_annual_utilisation_links,
    constr_min_annual_utilisation_links,
    constr_max_annual_utilisation_storage_discharge, 
    constr_min_annual_utilisation_storage_discharge, 
    constr_max_annual_utilisation_storage_charge,     
    constr_min_annual_utilisation_storage_charge,     
    constr_soc_intraday_profile,
    constr_soc_weekly_profile,
    constr_production_target_max,
    constr_production_target_min,
    apply_ramping_cost
)

import plotly.express as px
import pandas as pd     
import numpy as np
import xarray as xr
import os
os.environ['GRB_LICENSE_FILE'] = '/home/jy/opt/gurobi/gurobi.lic'

In [2]:
n = pypsa.Network()
# n.import_from_netcdf("/home/jy/Backup/client-earth_CE-A-OCCTO-004_v3/platform_network.nc") # calibration
n.import_from_netcdf("/home/jy/tz-amp/.amp/client-earth_CE-A-SEP7-006_a-batteriessen/platform_network.solved.nc")

INFO:pypsa.io:Imported network platform_network.solved.nc has buses, carriers, generators, links, loads, storage_units

In [10]:
n.generators.to_csv('generator.csv')

In [13]:
price_diff_df = pd.read_csv("data/old/generators_price_differential.csv", index_col=0)
old_names = n.generators[(n.generators.type == "gas-unspecified") | (n.generators.type == "coal-unspecified") | (n.generators.type == "gas-hydrogen-cofiring") | (n.generators.type == "coal-ammonia-cofiring") | (n.generators.type == "gas-ccs")].index
n.mremove("Generator", old_names)
n.import_components_from_dataframe(price_diff_df, "Generator")

In [4]:
# n.generators_t.marginal_cost.loc[:, n.generators_t.marginal_cost.filter(like="coal").columns] = n.generators_t.marginal_cost.loc[:, n.generators_t.marginal_cost.filter(like="coal-unspecified").columns].max().max()
# n.generators_t.marginal_cost.loc[:, n.generators_t.marginal_cost.filter(like="gas").columns] = n.generators_t.marginal_cost.loc[:, n.generators_t.marginal_cost.filter(like="gas-unspecified").columns].max().max()
n.generators_t.marginal_cost.loc[:, n.generators_t.marginal_cost.filter(like="nuclear").columns] = 12

In [48]:
n_solved = pypsa.Network()
n_solved.import_from_netcdf("/home/jy/tz-amp/.amp/client-earth_CE-A-SEP7-005_v3-dispatch-sen-nuc-testing-rampingcost/platform_network.solved.nc")

INFO:pypsa.io:Imported network platform_network.solved.nc has buses, carriers, generators, links, loads, storage_units

In [51]:
n_solved.generators.to_csv("nuclear_asset_level_data.csv")

In [45]:
n_solved.generators.loc[n_solved.generators.was_extendable][['p_nom', 'p_nom_expansion_opt']]

                                               p_nom  p_nom_expansion_opt
Generator
wind-offshore-unspecified:GRIDREGION-JPN-SH   1982.0          1981.999290
wind-offshore-unspecified:GRIDREGION-JPN-HR   1300.0          1300.000000
wind-offshore-unspecified:GRIDREGION-JPN-CB  10378.0         10377.990947
wind-offshore-unspecified:GRIDREGION-JPN-HK  14651.0         14650.000005
wind-offshore-unspecified:GRIDREGION-JPN-KA   1150.0          1149.999901
...                                              ...                  ...
gas-hydrogen-cofiring:GRIDREGION-JPN-KA       1448.0          1448.000000
gas-hydrogen-cofiring:GRIDREGION-JPN-CG       1056.0          1056.000000
gas-hydrogen-cofiring:GRIDREGION-JPN-TK       3779.0          3779.000000
gas-hydrogen-cofiring:GRIDREGION-JPN-TH        352.0           352.000000
gas-hydrogen-cofiring:GRIDREGION-JPN-KY        316.0           316.000000

[63 rows x 2 columns]

In [ ]:
n.generators.loc[n_solved.generators.p_nom_extendable, "p_nom"] = np.ceil(n_solved.generators.loc[n_solved.generators.p_nom_extendable, "p_nom_opt"])
n.storage_units.loc[n_solved.storage_units.p_nom_extendable, "p_nom"] = np.ceil(n_solved.storage_units.loc[n_solved.storage_units.p_nom_extendable, "p_nom_opt"])
# n.storage_units.loc[n_solved.storage_units.type == 'utility-scale', "p_nom"] = np.ceil(n_solved.storage_units.loc[n_solved.storage_units.type == 'utility-scale', "p_nom"])

In [ ]:
n.generators.p_nom_extendable = False
n.storage_units.p_nom_extendable = False

In [ ]:
new_nuclear_df = pd.read_csv("nuclear_asset_level_data.csv", index_col=0)
old_nuclear_names = n.generators[n.generators.type == "nuclear"].index
n.mremove("Generator", old_nuclear_names)
n.import_components_from_dataframe(new_nuclear_df, "Generator")

In [ ]:
n_nuc = pypsa.Network()
n_nuc.import_from_netcdf("/home/jy/tz-amp/.amp/client-earth_CE-A-SEP7-005_v1/platform_network.nc")

In [ ]:
n.generators.loc[n.generators.type == 'nuclear', 'p_nom'] = n_nuc.generators.loc[n_nuc.generators.type == 'nuclear', 'p_nom']

In [ ]:
n.generators.loc[:, "p_nom"] = np.ceil(n_solved.generators.loc[:, "p_nom_opt"])
n.storage_units.loc[:, "p_nom"] = np.ceil(n_solved.storage_units.loc[:, "p_nom_opt"])

In [3]:
n.generators['carrier'] = n.generators['type']
n.links['carrier'] = n.links['type']
n.storage_units['carrier'] = n.storage_units['type']

In [4]:
all_carriers = (
    n.generators.carrier.unique().tolist()
    + n.storage_units.carrier.unique().tolist()
    + n.links.carrier.unique().tolist()
)
missing_carriers = set(all_carriers) - set(n.carriers.index)
if missing_carriers:
    n.add("Carrier", missing_carriers)

n.generators.build_year = 2040
n.storage_units.build_year = 2040
n.links.build_year = 2040

In [ ]:
# n.storage_units_t.state_of_charge_set[:] = float("nan")
# n.storage_units_t.state_of_charge_set[n.storage_units_t.state_of_charge_set.notna().any(axis=1)]

In [ ]:
# p_nom for batteries
n.storage_units.loc[(n.storage_units.carrier == 'utility-scale') & (n.storage_units.bus == 'GRIDREGION-JPN-HK'), 'p_nom'] = 610
n.storage_units.loc[(n.storage_units.carrier == 'utility-scale') & (n.storage_units.bus == 'GRIDREGION-JPN-TH'), 'p_nom'] = 1711
n.storage_units.loc[(n.storage_units.carrier == 'utility-scale') & (n.storage_units.bus == 'GRIDREGION-JPN-TK'), 'p_nom'] = 6549
n.storage_units.loc[(n.storage_units.carrier == 'utility-scale') & (n.storage_units.bus == 'GRIDREGION-JPN-CB'), 'p_nom'] = 3034
n.storage_units.loc[(n.storage_units.carrier == 'utility-scale') & (n.storage_units.bus == 'GRIDREGION-JPN-HR'), 'p_nom'] = 616
n.storage_units.loc[(n.storage_units.carrier == 'utility-scale') & (n.storage_units.bus == 'GRIDREGION-JPN-KA'), 'p_nom'] = 3327
n.storage_units.loc[(n.storage_units.carrier == 'utility-scale') & (n.storage_units.bus == 'GRIDREGION-JPN-CG'), 'p_nom'] = 1273
n.storage_units.loc[(n.storage_units.carrier == 'utility-scale') & (n.storage_units.bus == 'GRIDREGION-JPN-SH'), 'p_nom'] = 592
n.storage_units.loc[(n.storage_units.carrier == 'utility-scale') & (n.storage_units.bus == 'GRIDREGION-JPN-KY'), 'p_nom'] = 1859

In [5]:
n.generators.loc[n.generators.carrier == 'wind-offshore-unspecified', 'p_nom_extendable'] = True
n.generators.loc[n.generators.carrier == 'wind-onshore', 'p_nom_extendable'] = True
n.generators.loc[n.generators.carrier == 'photovoltaic-unspecified', 'p_nom_extendable'] = True
n.generators.loc[n.generators.carrier == 'geothermal-unspecified', 'p_nom_extendable'] = True

n.generators.loc[n.generators.carrier == 'gas-ccs', 'p_nom_extendable'] = True
n.generators.loc[n.generators.carrier == 'coal-ammonia-cofiring', 'p_nom_extendable'] = True
n.generators.loc[n.generators.carrier == 'gas-hydrogen-cofiring', 'p_nom_extendable'] = True
n.storage_units.loc[n.storage_units.carrier == 'utility-scale', 'p_nom_extendable'] = True

In [ ]:
# p_nom for nuclear across different scenario
# Scenario A - 20% nuclear generation share which is the default capacity configuration on DWH

# # Scenario B - 12% nuclear generation share
# n.generators.loc[(n.generators.carrier == 'nuclear') & (n.generators.bus == 'GRIDREGION-JPN-HK'), 'p_nom'] = 2070
# n.generators.loc[(n.generators.carrier == 'nuclear') & (n.generators.bus == 'GRIDREGION-JPN-TH'), 'p_nom'] = 825
# n.generators.loc[(n.generators.carrier == 'nuclear') & (n.generators.bus == 'GRIDREGION-JPN-TK'), 'p_nom'] = 2712
# n.generators.loc[(n.generators.carrier == 'nuclear') & (n.generators.bus == 'GRIDREGION-JPN-CB'), 'p_nom'] = 0
# n.generators.loc[(n.generators.carrier == 'nuclear') & (n.generators.bus == 'GRIDREGION-JPN-HR'), 'p_nom'] = 1206
# n.generators.loc[(n.generators.carrier == 'nuclear') & (n.generators.bus == 'GRIDREGION-JPN-KA'), 'p_nom'] = 4100
# n.generators.loc[(n.generators.carrier == 'nuclear') & (n.generators.bus == 'GRIDREGION-JPN-CG'), 'p_nom'] = 820
# n.generators.loc[(n.generators.carrier == 'nuclear') & (n.generators.bus == 'GRIDREGION-JPN-SH'), 'p_nom'] = 890
# n.generators.loc[(n.generators.carrier == 'nuclear') & (n.generators.bus == 'GRIDREGION-JPN-KY'), 'p_nom'] = 4140

# Scenario C - 16% nuclear generation share
n.generators.loc[(n.generators.carrier == 'nuclear') & (n.generators.bus == 'GRIDREGION-JPN-HK'), 'p_nom'] = 2070
n.generators.loc[(n.generators.carrier == 'nuclear') & (n.generators.bus == 'GRIDREGION-JPN-TH'), 'p_nom'] = 2208
n.generators.loc[(n.generators.carrier == 'nuclear') & (n.generators.bus == 'GRIDREGION-JPN-TK'), 'p_nom'] = 3812
n.generators.loc[(n.generators.carrier == 'nuclear') & (n.generators.bus == 'GRIDREGION-JPN-CB'), 'p_nom'] = 0
n.generators.loc[(n.generators.carrier == 'nuclear') & (n.generators.bus == 'GRIDREGION-JPN-HR'), 'p_nom'] = 1206
n.generators.loc[(n.generators.carrier == 'nuclear') & (n.generators.bus == 'GRIDREGION-JPN-KA'), 'p_nom'] = 6578
n.generators.loc[(n.generators.carrier == 'nuclear') & (n.generators.bus == 'GRIDREGION-JPN-CG'), 'p_nom'] = 2193
n.generators.loc[(n.generators.carrier == 'nuclear') & (n.generators.bus == 'GRIDREGION-JPN-SH'), 'p_nom'] = 890
n.generators.loc[(n.generators.carrier == 'nuclear') & (n.generators.bus == 'GRIDREGION-JPN-KY'), 'p_nom'] = 4140

In [6]:
# set p_nom_min = p_nom to avoid capacity retirement
n.generators.p_nom_min = n.generators.p_nom

In [7]:
# Renewable p_nom_max
# p_nom_max for geothermal
n.generators.loc[n.generators.carrier == 'geothermal-unspecified', 'p_nom_max'] = n.generators.loc[n.generators.carrier == 'geothermal-unspecified', 'p_nom'] * 1.5

# p_nom_max for solar
n.generators.loc[(n.generators.carrier == 'photovoltaic-unspecified') & (n.generators.bus == 'GRIDREGION-JPN-HK'), 'p_nom_max'] = 8305 
n.generators.loc[(n.generators.carrier == 'photovoltaic-unspecified') & (n.generators.bus == 'GRIDREGION-JPN-TH'), 'p_nom_max'] = 33780 
n.generators.loc[(n.generators.carrier == 'photovoltaic-unspecified') & (n.generators.bus == 'GRIDREGION-JPN-TK'), 'p_nom_max'] = 60231 
n.generators.loc[(n.generators.carrier == 'photovoltaic-unspecified') & (n.generators.bus == 'GRIDREGION-JPN-CB'), 'p_nom_max'] = 38999 
n.generators.loc[(n.generators.carrier == 'photovoltaic-unspecified') & (n.generators.bus == 'GRIDREGION-JPN-HR'), 'p_nom_max'] = 4970 
n.generators.loc[(n.generators.carrier == 'photovoltaic-unspecified') & (n.generators.bus == 'GRIDREGION-JPN-KA'), 'p_nom_max'] = 23097 
n.generators.loc[(n.generators.carrier == 'photovoltaic-unspecified') & (n.generators.bus == 'GRIDREGION-JPN-CG'), 'p_nom_max'] = 26285 
n.generators.loc[(n.generators.carrier == 'photovoltaic-unspecified') & (n.generators.bus == 'GRIDREGION-JPN-SH'), 'p_nom_max'] = 13496 
n.generators.loc[(n.generators.carrier == 'photovoltaic-unspecified') & (n.generators.bus == 'GRIDREGION-JPN-KY'), 'p_nom_max'] = 49404

# p_nom_max for onshore wind
n.generators.loc[(n.generators.carrier == 'wind-onshore') & (n.generators.bus == 'GRIDREGION-JPN-HK'), 'p_nom_max'] = 6290
n.generators.loc[(n.generators.carrier == 'wind-onshore') & (n.generators.bus == 'GRIDREGION-JPN-TH'), 'p_nom_max'] = 18246
n.generators.loc[(n.generators.carrier == 'wind-onshore') & (n.generators.bus == 'GRIDREGION-JPN-TK'), 'p_nom_max'] = 3890
n.generators.loc[(n.generators.carrier == 'wind-onshore') & (n.generators.bus == 'GRIDREGION-JPN-CB'), 'p_nom_max'] = 1221
n.generators.loc[(n.generators.carrier == 'wind-onshore') & (n.generators.bus == 'GRIDREGION-JPN-HR'), 'p_nom_max'] = 1789
n.generators.loc[(n.generators.carrier == 'wind-onshore') & (n.generators.bus == 'GRIDREGION-JPN-KA'), 'p_nom_max'] = 2404
n.generators.loc[(n.generators.carrier == 'wind-onshore') & (n.generators.bus == 'GRIDREGION-JPN-CG'), 'p_nom_max'] = 2144
n.generators.loc[(n.generators.carrier == 'wind-onshore') & (n.generators.bus == 'GRIDREGION-JPN-SH'), 'p_nom_max'] = 1950
n.generators.loc[(n.generators.carrier == 'wind-onshore') & (n.generators.bus == 'GRIDREGION-JPN-KY'), 'p_nom_max'] = 3039

# p_nom_max for offshore wind
# Taking highest quality sites for each region
n.generators.loc[(n.generators.carrier == 'wind-offshore-unspecified') & (n.generators.bus == 'GRIDREGION-JPN-HK'), 'p_nom_max'] = 45106
n.generators.loc[(n.generators.carrier == 'wind-offshore-unspecified') & (n.generators.bus == 'GRIDREGION-JPN-TH'), 'p_nom_max'] = 24536
n.generators.loc[(n.generators.carrier == 'wind-offshore-unspecified') & (n.generators.bus == 'GRIDREGION-JPN-TK'), 'p_nom_max'] = 16176
n.generators.loc[(n.generators.carrier == 'wind-offshore-unspecified') & (n.generators.bus == 'GRIDREGION-JPN-CB'), 'p_nom_max'] = 10378
n.generators.loc[(n.generators.carrier == 'wind-offshore-unspecified') & (n.generators.bus == 'GRIDREGION-JPN-HR'), 'p_nom_max'] = 1300
n.generators.loc[(n.generators.carrier == 'wind-offshore-unspecified') & (n.generators.bus == 'GRIDREGION-JPN-KA'), 'p_nom_max'] = 1150
n.generators.loc[(n.generators.carrier == 'wind-offshore-unspecified') & (n.generators.bus == 'GRIDREGION-JPN-CG'), 'p_nom_max'] = 843
n.generators.loc[(n.generators.carrier == 'wind-offshore-unspecified') & (n.generators.bus == 'GRIDREGION-JPN-SH'), 'p_nom_max'] = 1982 
n.generators.loc[(n.generators.carrier == 'wind-offshore-unspecified') & (n.generators.bus == 'GRIDREGION-JPN-KY'), 'p_nom_max'] = 13141

# # p_nom_max for batteries
# n.storage_units.loc[(n.storage_units.carrier == 'utility-scale') & (n.storage_units.bus == 'GRIDREGION-JPN-HK'), 'p_nom_max'] = 610
# n.storage_units.loc[(n.storage_units.carrier == 'utility-scale') & (n.storage_units.bus == 'GRIDREGION-JPN-TH'), 'p_nom_max'] = 1711
# n.storage_units.loc[(n.storage_units.carrier == 'utility-scale') & (n.storage_units.bus == 'GRIDREGION-JPN-TK'), 'p_nom_max'] = 6549
# n.storage_units.loc[(n.storage_units.carrier == 'utility-scale') & (n.storage_units.bus == 'GRIDREGION-JPN-CB'), 'p_nom_max'] = 3034
# n.storage_units.loc[(n.storage_units.carrier == 'utility-scale') & (n.storage_units.bus == 'GRIDREGION-JPN-HR'), 'p_nom_max'] = 616
# n.storage_units.loc[(n.storage_units.carrier == 'utility-scale') & (n.storage_units.bus == 'GRIDREGION-JPN-KA'), 'p_nom_max'] = 3327
# n.storage_units.loc[(n.storage_units.carrier == 'utility-scale') & (n.storage_units.bus == 'GRIDREGION-JPN-CG'), 'p_nom_max'] = 1273
# n.storage_units.loc[(n.storage_units.carrier == 'utility-scale') & (n.storage_units.bus == 'GRIDREGION-JPN-SH'), 'p_nom_max'] = 592
# n.storage_units.loc[(n.storage_units.carrier == 'utility-scale') & (n.storage_units.bus == 'GRIDREGION-JPN-KY'), 'p_nom_max'] = 1859

In [8]:
# p_nom_max for coal-ammonia-cofiring
n.generators.loc[(n.generators.carrier == 'coal-ammonia-cofiring') & (n.generators.bus == 'GRIDREGION-JPN-HK'), 'p_nom_max'] = 700
n.generators.loc[(n.generators.carrier == 'coal-ammonia-cofiring') & (n.generators.bus == 'GRIDREGION-JPN-TH'), 'p_nom_max'] = 405
n.generators.loc[(n.generators.carrier == 'coal-ammonia-cofiring') & (n.generators.bus == 'GRIDREGION-JPN-TK'), 'p_nom_max'] = 997
n.generators.loc[(n.generators.carrier == 'coal-ammonia-cofiring') & (n.generators.bus == 'GRIDREGION-JPN-CB'), 'p_nom_max'] = 1000
n.generators.loc[(n.generators.carrier == 'coal-ammonia-cofiring') & (n.generators.bus == 'GRIDREGION-JPN-HR'), 'p_nom_max'] = 257
n.generators.loc[(n.generators.carrier == 'coal-ammonia-cofiring') & (n.generators.bus == 'GRIDREGION-JPN-KA'), 'p_nom_max'] = 1400
n.generators.loc[(n.generators.carrier == 'coal-ammonia-cofiring') & (n.generators.bus == 'GRIDREGION-JPN-CG'), 'p_nom_max'] = 810
n.generators.loc[(n.generators.carrier == 'coal-ammonia-cofiring') & (n.generators.bus == 'GRIDREGION-JPN-SH'), 'p_nom_max'] = 102 
n.generators.loc[(n.generators.carrier == 'coal-ammonia-cofiring') & (n.generators.bus == 'GRIDREGION-JPN-KY'), 'p_nom_max'] = 372

In [9]:
# p_nom_max for gas-hydrogen-cofiring
n.generators.loc[(n.generators.carrier == 'gas-hydrogen-cofiring') & (n.generators.bus == 'GRIDREGION-JPN-HK'), 'p_nom_max'] = 437
n.generators.loc[(n.generators.carrier == 'gas-hydrogen-cofiring') & (n.generators.bus == 'GRIDREGION-JPN-TH'), 'p_nom_max'] = 352
n.generators.loc[(n.generators.carrier == 'gas-hydrogen-cofiring') & (n.generators.bus == 'GRIDREGION-JPN-TK'), 'p_nom_max'] = 3779
n.generators.loc[(n.generators.carrier == 'gas-hydrogen-cofiring') & (n.generators.bus == 'GRIDREGION-JPN-CB'), 'p_nom_max'] = 1306
n.generators.loc[(n.generators.carrier == 'gas-hydrogen-cofiring') & (n.generators.bus == 'GRIDREGION-JPN-HR'), 'p_nom_max'] = 184
n.generators.loc[(n.generators.carrier == 'gas-hydrogen-cofiring') & (n.generators.bus == 'GRIDREGION-JPN-KA'), 'p_nom_max'] = 1448
n.generators.loc[(n.generators.carrier == 'gas-hydrogen-cofiring') & (n.generators.bus == 'GRIDREGION-JPN-CG'), 'p_nom_max'] = 1056
n.generators.loc[(n.generators.carrier == 'gas-hydrogen-cofiring') & (n.generators.bus == 'GRIDREGION-JPN-SH'), 'p_nom_max'] = 67
n.generators.loc[(n.generators.carrier == 'gas-hydrogen-cofiring') & (n.generators.bus == 'GRIDREGION-JPN-KY'), 'p_nom_max'] = 316

In [10]:
n.generators.groupby('type')[['p_nom', 'p_nom_max']].sum()

                                    p_nom  p_nom_max
type
biomass                            7220.0        inf
coal-ammonia-cofiring              3100.0     6043.0
coal-unspecified                  20997.0        inf
gas-ccs                             250.0        inf
gas-hydrogen-cofiring              1200.0     8945.0
gas-unspecified                   20133.0        inf
geothermal-unspecified             1550.0     2325.0
hydro-reservoir-and-run-of-river  23360.0        inf
nuclear                           27814.0        inf
photovoltaic-unspecified          75500.0   258567.0
wind-offshore-unspecified         45000.0   114612.0
wind-onshore                      11080.0    40973.0

In [14]:
n.generators.marginal_cost[n.generators.carrier == 'coal-ammonia-cofiring']

Generator
coal-ammonia-cofiring:GRIDREGION-JPN-SH    103.66
coal-ammonia-cofiring:GRIDREGION-JPN-HR    100.10
coal-ammonia-cofiring:GRIDREGION-JPN-CB    100.79
coal-ammonia-cofiring:GRIDREGION-JPN-HK    106.04
coal-ammonia-cofiring:GRIDREGION-JPN-KA    100.67
coal-ammonia-cofiring:GRIDREGION-JPN-CG    103.66
coal-ammonia-cofiring:GRIDREGION-JPN-TK    100.61
coal-ammonia-cofiring:GRIDREGION-JPN-TH    103.24
coal-ammonia-cofiring:GRIDREGION-JPN-KY    106.27
Name: marginal_cost, dtype: float64

In [ ]:
n.storage_units

In [15]:
n.generators.loc[(n.generators.carrier == 'coal-subcritical'), 'ramp_limit_up'] = 0.4
n.generators.loc[(n.generators.carrier == 'coal-subcritical'), 'ramp_limit_down'] = 0.4

n.generators.loc[(n.generators.carrier == 'coal-supercritical'), 'ramp_limit_up'] = 0.4
n.generators.loc[(n.generators.carrier == 'coal-supercritical'), 'ramp_limit_down'] = 0.4

n.generators.loc[(n.generators.carrier == 'coal-ammonia-cofiring'), 'ramp_limit_up'] = 0.4
n.generators.loc[(n.generators.carrier == 'coal-ammonia-cofiring'), 'ramp_limit_down'] = 0.4

n.generators.loc[(n.generators.carrier == 'gas-conventional'), 'ramp_limit_up'] = 0.9
n.generators.loc[(n.generators.carrier == 'gas-conventional'), 'ramp_limit_down'] = 0.9

n.generators.loc[(n.generators.carrier == 'gas-combined-cycle'), 'ramp_limit_up'] = 0.9
n.generators.loc[(n.generators.carrier == 'gas-combined-cycle'), 'ramp_limit_down'] = 0.9

n.generators.loc[(n.generators.carrier == 'gas-advanced-combined-cycle'), 'ramp_limit_up'] = 0.9
n.generators.loc[(n.generators.carrier == 'gas-advanced-combined-cycle'), 'ramp_limit_down'] = 0.9

n.generators.loc[(n.generators.carrier == 'gas-more-advanced-combined-cycle'), 'ramp_limit_up'] = 0.9
n.generators.loc[(n.generators.carrier == 'gas-more-advanced-combined-cycle'), 'ramp_limit_down'] = 0.9

n.generators.loc[(n.generators.carrier == 'gas-hydrogen-cofiring'), 'ramp_limit_up'] = 0.9
n.generators.loc[(n.generators.carrier == 'gas-hydrogen-cofiring'), 'ramp_limit_down'] = 0.9

n.generators.loc[(n.generators.carrier == 'gas-ccs'), 'ramp_limit_up'] = 0.9
n.generators.loc[(n.generators.carrier == 'gas-ccs'), 'ramp_limit_down'] = 0.9

n.generators.loc[(n.generators.carrier == 'nuclear'), 'ramp_limit_up'] = 0.6
n.generators.loc[(n.generators.carrier == 'nuclear'), 'ramp_limit_down'] = 0.6

In [16]:
n.storage_units.loc[n.storage_units.carrier == 'utility-scale', 'efficiency_store'] = 0.92
n.storage_units.loc[n.storage_units.carrier == 'utility-scale', 'efficiency_dispatch'] = 0.92
n.storage_units.loc[n.storage_units.carrier == 'utility-scale', 'marginal_cost'] = 1
n.storage_units.loc[n.storage_units.carrier == 'hydro-pumped-storage-unspecified', 'marginal_cost'] = 1

In [ ]:
n.generators.loc[n.generators.carrier == 'wind-offshore-unspecified', 'marginal_cost'] = -1
n.generators.loc[n.generators.carrier == 'wind-onshore', 'marginal_cost'] = -1
n.generators.loc[n.generators.carrier == 'photovoltaic-unspecified', 'marginal_cost'] = -1

In [17]:
n.generators.loc[n.generators.carrier == 'nuclear', 'p_min_pu'] = 0.7
n.generators.loc[n.generators.carrier == 'nuclear', 'p_max_pu'] = 0.7

In [ ]:
n.generators.loc[n.generators.carrier == 'nuclear', 'max_ramps_per_day'] = 2

In [18]:
n.generators_t.p_min_pu = n.generators_t.p_max_pu.filter(regex='biomass|geothermal|hydro')

In [19]:
# p_max_pu - coal-subcritical
n.generators.loc[(n.generators.carrier == 'coal-subcritical') & (n.generators.bus == 'GRIDREGION-JPN-HK'), 'p_max_pu'] = 0.46
n.generators.loc[(n.generators.carrier == 'coal-subcritical') & (n.generators.bus == 'GRIDREGION-JPN-TH'), 'p_max_pu'] = 0.57
n.generators.loc[(n.generators.carrier == 'coal-subcritical') & (n.generators.bus == 'GRIDREGION-JPN-TK'), 'p_max_pu'] = 0.62
n.generators.loc[(n.generators.carrier == 'coal-subcritical') & (n.generators.bus == 'GRIDREGION-JPN-CB'), 'p_max_pu'] = 0.63
n.generators.loc[(n.generators.carrier == 'coal-subcritical') & (n.generators.bus == 'GRIDREGION-JPN-HR'), 'p_max_pu'] = 0.60
n.generators.loc[(n.generators.carrier == 'coal-subcritical') & (n.generators.bus == 'GRIDREGION-JPN-KA'), 'p_max_pu'] = 0.60
n.generators.loc[(n.generators.carrier == 'coal-subcritical') & (n.generators.bus == 'GRIDREGION-JPN-CG'), 'p_max_pu'] = 0.52
n.generators.loc[(n.generators.carrier == 'coal-subcritical') & (n.generators.bus == 'GRIDREGION-JPN-SH'), 'p_max_pu'] = 0.59
n.generators.loc[(n.generators.carrier == 'coal-subcritical') & (n.generators.bus == 'GRIDREGION-JPN-KY'), 'p_max_pu'] = 0.51

# p_max_pu - coal-supercritical
n.generators.loc[(n.generators.carrier == 'coal-supercritical') & (n.generators.bus == 'GRIDREGION-JPN-HK'), 'p_max_pu'] = 0.46
n.generators.loc[(n.generators.carrier == 'coal-supercritical') & (n.generators.bus == 'GRIDREGION-JPN-TH'), 'p_max_pu'] = 0.57
n.generators.loc[(n.generators.carrier == 'coal-supercritical') & (n.generators.bus == 'GRIDREGION-JPN-TK'), 'p_max_pu'] = 0.62
n.generators.loc[(n.generators.carrier == 'coal-supercritical') & (n.generators.bus == 'GRIDREGION-JPN-CB'), 'p_max_pu'] = 0.63
n.generators.loc[(n.generators.carrier == 'coal-supercritical') & (n.generators.bus == 'GRIDREGION-JPN-HR'), 'p_max_pu'] = 0.60
n.generators.loc[(n.generators.carrier == 'coal-supercritical') & (n.generators.bus == 'GRIDREGION-JPN-KA'), 'p_max_pu'] = 0.60
n.generators.loc[(n.generators.carrier == 'coal-supercritical') & (n.generators.bus == 'GRIDREGION-JPN-CG'), 'p_max_pu'] = 0.52
n.generators.loc[(n.generators.carrier == 'coal-supercritical') & (n.generators.bus == 'GRIDREGION-JPN-SH'), 'p_max_pu'] = 0.59
n.generators.loc[(n.generators.carrier == 'coal-supercritical') & (n.generators.bus == 'GRIDREGION-JPN-KY'), 'p_max_pu'] = 0.51

# p_max_pu - coal-ammonia cofiring
n.generators.loc[(n.generators.carrier == 'coal-ammonia-cofiring') & (n.generators.bus == 'GRIDREGION-JPN-HK'), 'p_max_pu'] = 0.46
n.generators.loc[(n.generators.carrier == 'coal-ammonia-cofiring') & (n.generators.bus == 'GRIDREGION-JPN-TH'), 'p_max_pu'] = 0.57
n.generators.loc[(n.generators.carrier == 'coal-ammonia-cofiring') & (n.generators.bus == 'GRIDREGION-JPN-TK'), 'p_max_pu'] = 0.62
n.generators.loc[(n.generators.carrier == 'coal-ammonia-cofiring') & (n.generators.bus == 'GRIDREGION-JPN-CB'), 'p_max_pu'] = 0.63
n.generators.loc[(n.generators.carrier == 'coal-ammonia-cofiring') & (n.generators.bus == 'GRIDREGION-JPN-HR'), 'p_max_pu'] = 0.60
n.generators.loc[(n.generators.carrier == 'coal-ammonia-cofiring') & (n.generators.bus == 'GRIDREGION-JPN-KA'), 'p_max_pu'] = 0.60
n.generators.loc[(n.generators.carrier == 'coal-ammonia-cofiring') & (n.generators.bus == 'GRIDREGION-JPN-CG'), 'p_max_pu'] = 0.52
n.generators.loc[(n.generators.carrier == 'coal-ammonia-cofiring') & (n.generators.bus == 'GRIDREGION-JPN-SH'), 'p_max_pu'] = 0.59
n.generators.loc[(n.generators.carrier == 'coal-ammonia-cofiring') & (n.generators.bus == 'GRIDREGION-JPN-KY'), 'p_max_pu'] = 0.51

In [20]:
# max_utilisation_rate
# coal - subcritical
n.generators.loc[(n.generators.carrier == 'coal-subcritical') & (n.generators.bus == 'GRIDREGION-JPN-HK'), 'max_utilisation_rate'] = 0.22
n.generators.loc[(n.generators.carrier == 'coal-subcritical') & (n.generators.bus == 'GRIDREGION-JPN-TH'), 'max_utilisation_rate'] = 0.29
n.generators.loc[(n.generators.carrier == 'coal-subcritical') & (n.generators.bus == 'GRIDREGION-JPN-TK'), 'max_utilisation_rate'] = 0.34
n.generators.loc[(n.generators.carrier == 'coal-subcritical') & (n.generators.bus == 'GRIDREGION-JPN-CB'), 'max_utilisation_rate'] = 0.36
n.generators.loc[(n.generators.carrier == 'coal-subcritical') & (n.generators.bus == 'GRIDREGION-JPN-HR'), 'max_utilisation_rate'] = 0.34
n.generators.loc[(n.generators.carrier == 'coal-subcritical') & (n.generators.bus == 'GRIDREGION-JPN-KA'), 'max_utilisation_rate'] = 0.34
n.generators.loc[(n.generators.carrier == 'coal-subcritical') & (n.generators.bus == 'GRIDREGION-JPN-CG'), 'max_utilisation_rate'] = 0.27
n.generators.loc[(n.generators.carrier == 'coal-subcritical') & (n.generators.bus == 'GRIDREGION-JPN-SH'), 'max_utilisation_rate'] = 0.30
n.generators.loc[(n.generators.carrier == 'coal-subcritical') & (n.generators.bus == 'GRIDREGION-JPN-KY'), 'max_utilisation_rate'] = 0.24

# coal - supercritical
n.generators.loc[(n.generators.carrier == 'coal-supercritical') & (n.generators.bus == 'GRIDREGION-JPN-HK'), 'max_utilisation_rate'] = 0.45
n.generators.loc[(n.generators.carrier == 'coal-supercritical') & (n.generators.bus == 'GRIDREGION-JPN-TH'), 'max_utilisation_rate'] = 0.58
n.generators.loc[(n.generators.carrier == 'coal-supercritical') & (n.generators.bus == 'GRIDREGION-JPN-TK'), 'max_utilisation_rate'] = 0.68
n.generators.loc[(n.generators.carrier == 'coal-supercritical') & (n.generators.bus == 'GRIDREGION-JPN-CB'), 'max_utilisation_rate'] = 0.72
n.generators.loc[(n.generators.carrier == 'coal-supercritical') & (n.generators.bus == 'GRIDREGION-JPN-HR'), 'max_utilisation_rate'] = 0.67
n.generators.loc[(n.generators.carrier == 'coal-supercritical') & (n.generators.bus == 'GRIDREGION-JPN-KA'), 'max_utilisation_rate'] = 0.68
n.generators.loc[(n.generators.carrier == 'coal-supercritical') & (n.generators.bus == 'GRIDREGION-JPN-CG'), 'max_utilisation_rate'] = 0.54
n.generators.loc[(n.generators.carrier == 'coal-supercritical') & (n.generators.bus == 'GRIDREGION-JPN-SH'), 'max_utilisation_rate'] = 0.59
n.generators.loc[(n.generators.carrier == 'coal-supercritical') & (n.generators.bus == 'GRIDREGION-JPN-KY'), 'max_utilisation_rate'] = 0.48

# coal-ammonia cofiring
n.generators.loc[(n.generators.carrier == 'coal-ammonia-cofiring') & (n.generators.bus == 'GRIDREGION-JPN-HK'), 'max_utilisation_rate'] = 0.34
n.generators.loc[(n.generators.carrier == 'coal-ammonia-cofiring') & (n.generators.bus == 'GRIDREGION-JPN-TH'), 'max_utilisation_rate'] = 0.445
n.generators.loc[(n.generators.carrier == 'coal-ammonia-cofiring') & (n.generators.bus == 'GRIDREGION-JPN-TK'), 'max_utilisation_rate'] = 0.52
n.generators.loc[(n.generators.carrier == 'coal-ammonia-cofiring') & (n.generators.bus == 'GRIDREGION-JPN-CB'), 'max_utilisation_rate'] = 0.55
n.generators.loc[(n.generators.carrier == 'coal-ammonia-cofiring') & (n.generators.bus == 'GRIDREGION-JPN-HR'), 'max_utilisation_rate'] = 0.51
n.generators.loc[(n.generators.carrier == 'coal-ammonia-cofiring') & (n.generators.bus == 'GRIDREGION-JPN-KA'), 'max_utilisation_rate'] = 0.52
n.generators.loc[(n.generators.carrier == 'coal-ammonia-cofiring') & (n.generators.bus == 'GRIDREGION-JPN-CG'), 'max_utilisation_rate'] = 0.41
n.generators.loc[(n.generators.carrier == 'coal-ammonia-cofiring') & (n.generators.bus == 'GRIDREGION-JPN-SH'), 'max_utilisation_rate'] = 0.45
n.generators.loc[(n.generators.carrier == 'coal-ammonia-cofiring') & (n.generators.bus == 'GRIDREGION-JPN-KY'), 'max_utilisation_rate'] = 0.365

# gas-conventional
n.generators.loc[(n.generators.carrier == 'gas-conventional') & (n.generators.bus == 'GRIDREGION-JPN-HK'), 'max_utilisation_rate'] = 0.70
n.generators.loc[(n.generators.carrier == 'gas-conventional') & (n.generators.bus == 'GRIDREGION-JPN-TH'), 'max_utilisation_rate'] = 0.70
n.generators.loc[(n.generators.carrier == 'gas-conventional') & (n.generators.bus == 'GRIDREGION-JPN-TK'), 'max_utilisation_rate'] = 0.70
n.generators.loc[(n.generators.carrier == 'gas-conventional') & (n.generators.bus == 'GRIDREGION-JPN-CB'), 'max_utilisation_rate'] = 0.70
n.generators.loc[(n.generators.carrier == 'gas-conventional') & (n.generators.bus == 'GRIDREGION-JPN-HR'), 'max_utilisation_rate'] = 0.70
n.generators.loc[(n.generators.carrier == 'gas-conventional') & (n.generators.bus == 'GRIDREGION-JPN-KA'), 'max_utilisation_rate'] = 0.70
n.generators.loc[(n.generators.carrier == 'gas-conventional') & (n.generators.bus == 'GRIDREGION-JPN-CG'), 'max_utilisation_rate'] = 0.70
n.generators.loc[(n.generators.carrier == 'gas-conventional') & (n.generators.bus == 'GRIDREGION-JPN-SH'), 'max_utilisation_rate'] = 0.70
n.generators.loc[(n.generators.carrier == 'gas-conventional') & (n.generators.bus == 'GRIDREGION-JPN-KY'), 'max_utilisation_rate'] = 0.70

# gas-combined-cycle
n.generators.loc[(n.generators.carrier == 'gas-combined-cycle') & (n.generators.bus == 'GRIDREGION-JPN-HK'), 'max_utilisation_rate'] = 0.70
n.generators.loc[(n.generators.carrier == 'gas-combined-cycle') & (n.generators.bus == 'GRIDREGION-JPN-TH'), 'max_utilisation_rate'] = 0.70
n.generators.loc[(n.generators.carrier == 'gas-combined-cycle') & (n.generators.bus == 'GRIDREGION-JPN-TK'), 'max_utilisation_rate'] = 0.70
n.generators.loc[(n.generators.carrier == 'gas-combined-cycle') & (n.generators.bus == 'GRIDREGION-JPN-CB'), 'max_utilisation_rate'] = 0.70
n.generators.loc[(n.generators.carrier == 'gas-combined-cycle') & (n.generators.bus == 'GRIDREGION-JPN-HR'), 'max_utilisation_rate'] = 0.70
n.generators.loc[(n.generators.carrier == 'gas-combined-cycle') & (n.generators.bus == 'GRIDREGION-JPN-KA'), 'max_utilisation_rate'] = 0.70
n.generators.loc[(n.generators.carrier == 'gas-combined-cycle') & (n.generators.bus == 'GRIDREGION-JPN-CG'), 'max_utilisation_rate'] = 0.70
n.generators.loc[(n.generators.carrier == 'gas-combined-cycle') & (n.generators.bus == 'GRIDREGION-JPN-SH'), 'max_utilisation_rate'] = 0.70
n.generators.loc[(n.generators.carrier == 'gas-combined-cycle') & (n.generators.bus == 'GRIDREGION-JPN-KY'), 'max_utilisation_rate'] = 0.70

# gas-advanced-combined-cycle
n.generators.loc[(n.generators.carrier == 'gas-advanced-combined-cycle') & (n.generators.bus == 'GRIDREGION-JPN-HK'), 'max_utilisation_rate'] = 0.70
n.generators.loc[(n.generators.carrier == 'gas-advanced-combined-cycle') & (n.generators.bus == 'GRIDREGION-JPN-TH'), 'max_utilisation_rate'] = 0.70
n.generators.loc[(n.generators.carrier == 'gas-advanced-combined-cycle') & (n.generators.bus == 'GRIDREGION-JPN-TK'), 'max_utilisation_rate'] = 0.70
n.generators.loc[(n.generators.carrier == 'gas-advanced-combined-cycle') & (n.generators.bus == 'GRIDREGION-JPN-CB'), 'max_utilisation_rate'] = 0.70
n.generators.loc[(n.generators.carrier == 'gas-advanced-combined-cycle') & (n.generators.bus == 'GRIDREGION-JPN-HR'), 'max_utilisation_rate'] = 0.70
n.generators.loc[(n.generators.carrier == 'gas-advanced-combined-cycle') & (n.generators.bus == 'GRIDREGION-JPN-KA'), 'max_utilisation_rate'] = 0.70
n.generators.loc[(n.generators.carrier == 'gas-advanced-combined-cycle') & (n.generators.bus == 'GRIDREGION-JPN-CG'), 'max_utilisation_rate'] = 0.70
n.generators.loc[(n.generators.carrier == 'gas-advanced-combined-cycle') & (n.generators.bus == 'GRIDREGION-JPN-SH'), 'max_utilisation_rate'] = 0.70
n.generators.loc[(n.generators.carrier == 'gas-advanced-combined-cycle') & (n.generators.bus == 'GRIDREGION-JPN-KY'), 'max_utilisation_rate'] = 0.70

# gas-more-advanced-combined-cycle
n.generators.loc[(n.generators.carrier == 'gas-more-advanced-combined-cycle') & (n.generators.bus == 'GRIDREGION-JPN-HK'), 'max_utilisation_rate'] = 0.70
n.generators.loc[(n.generators.carrier == 'gas-more-advanced-combined-cycle') & (n.generators.bus == 'GRIDREGION-JPN-TH'), 'max_utilisation_rate'] = 0.70
n.generators.loc[(n.generators.carrier == 'gas-more-advanced-combined-cycle') & (n.generators.bus == 'GRIDREGION-JPN-TK'), 'max_utilisation_rate'] = 0.70
n.generators.loc[(n.generators.carrier == 'gas-more-advanced-combined-cycle') & (n.generators.bus == 'GRIDREGION-JPN-CB'), 'max_utilisation_rate'] = 0.70
n.generators.loc[(n.generators.carrier == 'gas-more-advanced-combined-cycle') & (n.generators.bus == 'GRIDREGION-JPN-HR'), 'max_utilisation_rate'] = 0.70
n.generators.loc[(n.generators.carrier == 'gas-more-advanced-combined-cycle') & (n.generators.bus == 'GRIDREGION-JPN-KA'), 'max_utilisation_rate'] = 0.70
n.generators.loc[(n.generators.carrier == 'gas-more-advanced-combined-cycle') & (n.generators.bus == 'GRIDREGION-JPN-CG'), 'max_utilisation_rate'] = 0.70
n.generators.loc[(n.generators.carrier == 'gas-more-advanced-combined-cycle') & (n.generators.bus == 'GRIDREGION-JPN-SH'), 'max_utilisation_rate'] = 0.70
n.generators.loc[(n.generators.carrier == 'gas-more-advanced-combined-cycle') & (n.generators.bus == 'GRIDREGION-JPN-KY'), 'max_utilisation_rate'] = 0.70

# gas-ccs
n.generators.loc[(n.generators.carrier == 'gas-ccs') & (n.generators.bus == 'GRIDREGION-JPN-HK'), 'max_utilisation_rate'] = 0.70
n.generators.loc[(n.generators.carrier == 'gas-ccs') & (n.generators.bus == 'GRIDREGION-JPN-TH'), 'max_utilisation_rate'] = 0.70
n.generators.loc[(n.generators.carrier == 'gas-ccs') & (n.generators.bus == 'GRIDREGION-JPN-TK'), 'max_utilisation_rate'] = 0.70
n.generators.loc[(n.generators.carrier == 'gas-ccs') & (n.generators.bus == 'GRIDREGION-JPN-CB'), 'max_utilisation_rate'] = 0.70
n.generators.loc[(n.generators.carrier == 'gas-ccs') & (n.generators.bus == 'GRIDREGION-JPN-HR'), 'max_utilisation_rate'] = 0.70
n.generators.loc[(n.generators.carrier == 'gas-ccs') & (n.generators.bus == 'GRIDREGION-JPN-KA'), 'max_utilisation_rate'] = 0.70
n.generators.loc[(n.generators.carrier == 'gas-ccs') & (n.generators.bus == 'GRIDREGION-JPN-CG'), 'max_utilisation_rate'] = 0.70
n.generators.loc[(n.generators.carrier == 'gas-ccs') & (n.generators.bus == 'GRIDREGION-JPN-SH'), 'max_utilisation_rate'] = 0.70
n.generators.loc[(n.generators.carrier == 'gas-ccs') & (n.generators.bus == 'GRIDREGION-JPN-KY'), 'max_utilisation_rate'] = 0.70

# gas-hydrogen-cofiring
n.generators.loc[(n.generators.carrier == 'gas-hydrogen-cofiring') & (n.generators.bus == 'GRIDREGION-JPN-HK'), 'max_utilisation_rate'] = 0.70
n.generators.loc[(n.generators.carrier == 'gas-hydrogen-cofiring') & (n.generators.bus == 'GRIDREGION-JPN-TH'), 'max_utilisation_rate'] = 0.70
n.generators.loc[(n.generators.carrier == 'gas-hydrogen-cofiring') & (n.generators.bus == 'GRIDREGION-JPN-TK'), 'max_utilisation_rate'] = 0.70
n.generators.loc[(n.generators.carrier == 'gas-hydrogen-cofiring') & (n.generators.bus == 'GRIDREGION-JPN-CB'), 'max_utilisation_rate'] = 0.70
n.generators.loc[(n.generators.carrier == 'gas-hydrogen-cofiring') & (n.generators.bus == 'GRIDREGION-JPN-HR'), 'max_utilisation_rate'] = 0.70
n.generators.loc[(n.generators.carrier == 'gas-hydrogen-cofiring') & (n.generators.bus == 'GRIDREGION-JPN-KA'), 'max_utilisation_rate'] = 0.70
n.generators.loc[(n.generators.carrier == 'gas-hydrogen-cofiring') & (n.generators.bus == 'GRIDREGION-JPN-CG'), 'max_utilisation_rate'] = 0.70
n.generators.loc[(n.generators.carrier == 'gas-hydrogen-cofiring') & (n.generators.bus == 'GRIDREGION-JPN-SH'), 'max_utilisation_rate'] = 0.70
n.generators.loc[(n.generators.carrier == 'gas-hydrogen-cofiring') & (n.generators.bus == 'GRIDREGION-JPN-KY'), 'max_utilisation_rate'] = 0.70

# # nuclear
# n.generators.loc[(n.generators.carrier == 'nuclear'), 'max_utilisation_rate'] = 0.70

In [21]:
# min_utilisation_rate
# coal - subcritical
n.generators.loc[(n.generators.carrier == 'coal-subcritical') & (n.generators.bus == 'GRIDREGION-JPN-HK'), 'min_utilisation_rate'] = 0.22
n.generators.loc[(n.generators.carrier == 'coal-subcritical') & (n.generators.bus == 'GRIDREGION-JPN-TH'), 'min_utilisation_rate'] = 0.29
n.generators.loc[(n.generators.carrier == 'coal-subcritical') & (n.generators.bus == 'GRIDREGION-JPN-TK'), 'min_utilisation_rate'] = 0.34
n.generators.loc[(n.generators.carrier == 'coal-subcritical') & (n.generators.bus == 'GRIDREGION-JPN-KY'), 'min_utilisation_rate'] = 0.24

# coal - supercritical
n.generators.loc[(n.generators.carrier == 'coal-supercritical') & (n.generators.bus == 'GRIDREGION-JPN-HK'), 'min_utilisation_rate'] = 0.34
n.generators.loc[(n.generators.carrier == 'coal-supercritical') & (n.generators.bus == 'GRIDREGION-JPN-TH'), 'min_utilisation_rate'] = 0.445
n.generators.loc[(n.generators.carrier == 'coal-supercritical') & (n.generators.bus == 'GRIDREGION-JPN-TK'), 'min_utilisation_rate'] = 0.52
n.generators.loc[(n.generators.carrier == 'coal-supercritical') & (n.generators.bus == 'GRIDREGION-JPN-KY'), 'min_utilisation_rate'] = 0.365

# coal-ammonia-cofiring
n.generators.loc[(n.generators.carrier == 'coal-ammonia-cofiring') & (n.generators.bus == 'GRIDREGION-JPN-HK'), 'min_utilisation_rate'] = 0.34
n.generators.loc[(n.generators.carrier == 'coal-ammonia-cofiring') & (n.generators.bus == 'GRIDREGION-JPN-TH'), 'min_utilisation_rate'] = 0.445
n.generators.loc[(n.generators.carrier == 'coal-ammonia-cofiring') & (n.generators.bus == 'GRIDREGION-JPN-TK'), 'min_utilisation_rate'] = 0.52
n.generators.loc[(n.generators.carrier == 'coal-ammonia-cofiring') & (n.generators.bus == 'GRIDREGION-JPN-KY'), 'min_utilisation_rate'] = 0.365


# gas - calibration constraints
n.generators.loc[(n.generators.carrier == 'gas-conventional') & (n.generators.bus == 'GRIDREGION-JPN-HK'), 'min_utilisation_rate'] = 0.14
n.generators.loc[(n.generators.carrier == 'gas-conventional') & (n.generators.bus == 'GRIDREGION-JPN-TH'), 'min_utilisation_rate'] = 0.095
n.generators.loc[(n.generators.carrier == 'gas-conventional') & (n.generators.bus == 'GRIDREGION-JPN-TK'), 'min_utilisation_rate'] = 0.16
n.generators.loc[(n.generators.carrier == 'gas-conventional') & (n.generators.bus == 'GRIDREGION-JPN-CB'), 'min_utilisation_rate'] = 0.23
n.generators.loc[(n.generators.carrier == 'gas-conventional') & (n.generators.bus == 'GRIDREGION-JPN-HR'), 'min_utilisation_rate'] = 0.10
n.generators.loc[(n.generators.carrier == 'gas-conventional') & (n.generators.bus == 'GRIDREGION-JPN-KA'), 'min_utilisation_rate'] = 0.225
n.generators.loc[(n.generators.carrier == 'gas-conventional') & (n.generators.bus == 'GRIDREGION-JPN-CG'), 'min_utilisation_rate'] = 0.05
n.generators.loc[(n.generators.carrier == 'gas-conventional') & (n.generators.bus == 'GRIDREGION-JPN-SH'), 'min_utilisation_rate'] = 0.085
n.generators.loc[(n.generators.carrier == 'gas-conventional') & (n.generators.bus == 'GRIDREGION-JPN-KY'), 'min_utilisation_rate'] = 0.04

# gas - calibration constraints
n.generators.loc[(n.generators.carrier == 'gas-combined-cycle') & (n.generators.bus == 'GRIDREGION-JPN-HK'), 'min_utilisation_rate'] = 0.14
n.generators.loc[(n.generators.carrier == 'gas-combined-cycle') & (n.generators.bus == 'GRIDREGION-JPN-TH'), 'min_utilisation_rate'] = 0.095
n.generators.loc[(n.generators.carrier == 'gas-combined-cycle') & (n.generators.bus == 'GRIDREGION-JPN-TK'), 'min_utilisation_rate'] = 0.16
n.generators.loc[(n.generators.carrier == 'gas-combined-cycle') & (n.generators.bus == 'GRIDREGION-JPN-CB'), 'min_utilisation_rate'] = 0.23
n.generators.loc[(n.generators.carrier == 'gas-combined-cycle') & (n.generators.bus == 'GRIDREGION-JPN-HR'), 'min_utilisation_rate'] = 0.10
n.generators.loc[(n.generators.carrier == 'gas-combined-cycle') & (n.generators.bus == 'GRIDREGION-JPN-KA'), 'min_utilisation_rate'] = 0.225
n.generators.loc[(n.generators.carrier == 'gas-combined-cycle') & (n.generators.bus == 'GRIDREGION-JPN-CG'), 'min_utilisation_rate'] = 0.05
n.generators.loc[(n.generators.carrier == 'gas-combined-cycle') & (n.generators.bus == 'GRIDREGION-JPN-SH'), 'min_utilisation_rate'] = 0.085
n.generators.loc[(n.generators.carrier == 'gas-combined-cycle') & (n.generators.bus == 'GRIDREGION-JPN-KY'), 'min_utilisation_rate'] = 0.04

# gas - calibration constraints
n.generators.loc[(n.generators.carrier == 'gas-advanced-combined-cycle') & (n.generators.bus == 'GRIDREGION-JPN-HK'), 'min_utilisation_rate'] = 0.14
n.generators.loc[(n.generators.carrier == 'gas-advanced-combined-cycle') & (n.generators.bus == 'GRIDREGION-JPN-TH'), 'min_utilisation_rate'] = 0.095
n.generators.loc[(n.generators.carrier == 'gas-advanced-combined-cycle') & (n.generators.bus == 'GRIDREGION-JPN-TK'), 'min_utilisation_rate'] = 0.16
n.generators.loc[(n.generators.carrier == 'gas-advanced-combined-cycle') & (n.generators.bus == 'GRIDREGION-JPN-CB'), 'min_utilisation_rate'] = 0.23
n.generators.loc[(n.generators.carrier == 'gas-advanced-combined-cycle') & (n.generators.bus == 'GRIDREGION-JPN-HR'), 'min_utilisation_rate'] = 0.10
n.generators.loc[(n.generators.carrier == 'gas-advanced-combined-cycle') & (n.generators.bus == 'GRIDREGION-JPN-KA'), 'min_utilisation_rate'] = 0.225
n.generators.loc[(n.generators.carrier == 'gas-advanced-combined-cycle') & (n.generators.bus == 'GRIDREGION-JPN-CG'), 'min_utilisation_rate'] = 0.05
n.generators.loc[(n.generators.carrier == 'gas-advanced-combined-cycle') & (n.generators.bus == 'GRIDREGION-JPN-SH'), 'min_utilisation_rate'] = 0.085
n.generators.loc[(n.generators.carrier == 'gas-advanced-combined-cycle') & (n.generators.bus == 'GRIDREGION-JPN-KY'), 'min_utilisation_rate'] = 0.04

# gas - calibration constraints
n.generators.loc[(n.generators.carrier == 'gas-more-advanced-combined-cycle') & (n.generators.bus == 'GRIDREGION-JPN-HK'), 'min_utilisation_rate'] = 0.14
n.generators.loc[(n.generators.carrier == 'gas-more-advanced-combined-cycle') & (n.generators.bus == 'GRIDREGION-JPN-TH'), 'min_utilisation_rate'] = 0.095
n.generators.loc[(n.generators.carrier == 'gas-more-advanced-combined-cycle') & (n.generators.bus == 'GRIDREGION-JPN-TK'), 'min_utilisation_rate'] = 0.16
n.generators.loc[(n.generators.carrier == 'gas-more-advanced-combined-cycle') & (n.generators.bus == 'GRIDREGION-JPN-CB'), 'min_utilisation_rate'] = 0.23
n.generators.loc[(n.generators.carrier == 'gas-more-advanced-combined-cycle') & (n.generators.bus == 'GRIDREGION-JPN-HR'), 'min_utilisation_rate'] = 0.10
n.generators.loc[(n.generators.carrier == 'gas-more-advanced-combined-cycle') & (n.generators.bus == 'GRIDREGION-JPN-KA'), 'min_utilisation_rate'] = 0.225
n.generators.loc[(n.generators.carrier == 'gas-more-advanced-combined-cycle') & (n.generators.bus == 'GRIDREGION-JPN-CG'), 'min_utilisation_rate'] = 0.05
n.generators.loc[(n.generators.carrier == 'gas-more-advanced-combined-cycle') & (n.generators.bus == 'GRIDREGION-JPN-SH'), 'min_utilisation_rate'] = 0.085
n.generators.loc[(n.generators.carrier == 'gas-more-advanced-combined-cycle') & (n.generators.bus == 'GRIDREGION-JPN-KY'), 'min_utilisation_rate'] = 0.04

# Assume gas-hydrogen-cofiring to follow the same min utilisation rate as gas to reflect the same level of operational constraints
n.generators.loc[(n.generators.carrier == 'gas-hydrogen-cofiring') & (n.generators.bus == 'GRIDREGION-JPN-HK'), 'min_utilisation_rate'] = 0.14
n.generators.loc[(n.generators.carrier == 'gas-hydrogen-cofiring') & (n.generators.bus == 'GRIDREGION-JPN-TH'), 'min_utilisation_rate'] = 0.095
n.generators.loc[(n.generators.carrier == 'gas-hydrogen-cofiring') & (n.generators.bus == 'GRIDREGION-JPN-TK'), 'min_utilisation_rate'] = 0.16
n.generators.loc[(n.generators.carrier == 'gas-hydrogen-cofiring') & (n.generators.bus == 'GRIDREGION-JPN-CB'), 'min_utilisation_rate'] = 0.23
n.generators.loc[(n.generators.carrier == 'gas-hydrogen-cofiring') & (n.generators.bus == 'GRIDREGION-JPN-HR'), 'min_utilisation_rate'] = 0.10
n.generators.loc[(n.generators.carrier == 'gas-hydrogen-cofiring') & (n.generators.bus == 'GRIDREGION-JPN-KA'), 'min_utilisation_rate'] = 0.225
n.generators.loc[(n.generators.carrier == 'gas-hydrogen-cofiring') & (n.generators.bus == 'GRIDREGION-JPN-CG'), 'min_utilisation_rate'] = 0.05
n.generators.loc[(n.generators.carrier == 'gas-hydrogen-cofiring') & (n.generators.bus == 'GRIDREGION-JPN-SH'), 'min_utilisation_rate'] = 0.085
n.generators.loc[(n.generators.carrier == 'gas-hydrogen-cofiring') & (n.generators.bus == 'GRIDREGION-JPN-KY'), 'min_utilisation_rate'] = 0.04

# Assume gas-ccs to follow the same min utilisation rate as gas to reflect the same level of operational constraints
n.generators.loc[(n.generators.carrier == 'gas-ccs') & (n.generators.bus == 'GRIDREGION-JPN-HK'), 'min_utilisation_rate'] = 0.14
n.generators.loc[(n.generators.carrier == 'gas-ccs') & (n.generators.bus == 'GRIDREGION-JPN-TH'), 'min_utilisation_rate'] = 0.095
n.generators.loc[(n.generators.carrier == 'gas-ccs') & (n.generators.bus == 'GRIDREGION-JPN-TK'), 'min_utilisation_rate'] = 0.16
n.generators.loc[(n.generators.carrier == 'gas-ccs') & (n.generators.bus == 'GRIDREGION-JPN-CB'), 'min_utilisation_rate'] = 0.23
n.generators.loc[(n.generators.carrier == 'gas-ccs') & (n.generators.bus == 'GRIDREGION-JPN-HR'), 'min_utilisation_rate'] = 0.10
n.generators.loc[(n.generators.carrier == 'gas-ccs') & (n.generators.bus == 'GRIDREGION-JPN-KA'), 'min_utilisation_rate'] = 0.225
n.generators.loc[(n.generators.carrier == 'gas-ccs') & (n.generators.bus == 'GRIDREGION-JPN-CG'), 'min_utilisation_rate'] = 0.05
n.generators.loc[(n.generators.carrier == 'gas-ccs') & (n.generators.bus == 'GRIDREGION-JPN-SH'), 'min_utilisation_rate'] = 0.085
n.generators.loc[(n.generators.carrier == 'gas-ccs') & (n.generators.bus == 'GRIDREGION-JPN-KY'), 'min_utilisation_rate'] = 0.04

In [22]:
# max_utilisation_rate - transmission
n.links.loc[(n.links.index == 'transmission:GRIDREGION-JPN-HK~GRIDREGION-JPN-TH'), 'max_utilisation_rate'] = 0.48
n.links.loc[(n.links.index == 'transmission:GRIDREGION-JPN-TH~GRIDREGION-JPN-HK'), 'max_utilisation_rate'] = 0.00
n.links.loc[(n.links.index == 'transmission:GRIDREGION-JPN-TH~GRIDREGION-JPN-TK'), 'max_utilisation_rate'] = 0.5875
n.links.loc[(n.links.index == 'transmission:GRIDREGION-JPN-TK~GRIDREGION-JPN-TH'), 'max_utilisation_rate'] = 0.00
n.links.loc[(n.links.index == 'transmission:GRIDREGION-JPN-TK~GRIDREGION-JPN-CB'), 'max_utilisation_rate'] = 0.44
n.links.loc[(n.links.index == 'transmission:GRIDREGION-JPN-CB~GRIDREGION-JPN-SH'), 'max_utilisation_rate'] = 0.00
n.links.loc[(n.links.index == 'transmission:GRIDREGION-JPN-CB~GRIDREGION-JPN-TK'), 'max_utilisation_rate'] = 0.25
n.links.loc[(n.links.index == 'transmission:GRIDREGION-JPN-CB~GRIDREGION-JPN-HR'), 'max_utilisation_rate'] = 0.02
n.links.loc[(n.links.index == 'transmission:GRIDREGION-JPN-CB~GRIDREGION-JPN-KA'), 'max_utilisation_rate'] = 0.04
n.links.loc[(n.links.index == 'transmission:GRIDREGION-JPN-HR~GRIDREGION-JPN-CB'), 'max_utilisation_rate'] = 0.33
n.links.loc[(n.links.index == 'transmission:GRIDREGION-JPN-HR~GRIDREGION-JPN-KA'), 'max_utilisation_rate'] = 0.18
n.links.loc[(n.links.index == 'transmission:GRIDREGION-JPN-KA~GRIDREGION-JPN-HR'), 'max_utilisation_rate'] = 0.09
n.links.loc[(n.links.index == 'transmission:GRIDREGION-JPN-KA~GRIDREGION-JPN-CB'), 'max_utilisation_rate'] = 0.25
n.links.loc[(n.links.index == 'transmission:GRIDREGION-JPN-KA~GRIDREGION-JPN-CG'), 'max_utilisation_rate'] = 0.19
n.links.loc[(n.links.index == 'transmission:GRIDREGION-JPN-KA~GRIDREGION-JPN-SH'), 'max_utilisation_rate'] = 0.00
n.links.loc[(n.links.index == 'transmission:GRIDREGION-JPN-CG~GRIDREGION-JPN-KA'), 'max_utilisation_rate'] = 0.40
n.links.loc[(n.links.index == 'transmission:GRIDREGION-JPN-CG~GRIDREGION-JPN-SH'), 'max_utilisation_rate'] = 0.00
n.links.loc[(n.links.index == 'transmission:GRIDREGION-JPN-SH~GRIDREGION-JPN-KY'), 'max_utilisation_rate'] = 0.00
n.links.loc[(n.links.index == 'transmission:GRIDREGION-JPN-KY~GRIDREGION-JPN-CG'), 'max_utilisation_rate'] = 0.34
n.links.loc[(n.links.index == 'transmission:GRIDREGION-JPN-KY~GRIDREGION-JPN-SH'), 'max_utilisation_rate'] = 0.83

In [23]:
# max_utilisation_rate - transmission
n.links.loc[(n.links.index == 'transmission:GRIDREGION-JPN-HK~GRIDREGION-JPN-TH'), 'max_utilisation_rate'] = 0.48 + 0.025
n.links.loc[(n.links.index == 'transmission:GRIDREGION-JPN-TH~GRIDREGION-JPN-HK'), 'max_utilisation_rate'] = 0.00 + 0.025
n.links.loc[(n.links.index == 'transmission:GRIDREGION-JPN-TH~GRIDREGION-JPN-TK'), 'max_utilisation_rate'] = 0.5875 + 0.025
n.links.loc[(n.links.index == 'transmission:GRIDREGION-JPN-TK~GRIDREGION-JPN-TH'), 'max_utilisation_rate'] = 0.00 + 0.025
n.links.loc[(n.links.index == 'transmission:GRIDREGION-JPN-TK~GRIDREGION-JPN-CB'), 'max_utilisation_rate'] = 0.44 + 0.025
n.links.loc[(n.links.index == 'transmission:GRIDREGION-JPN-CB~GRIDREGION-JPN-SH'), 'max_utilisation_rate'] = 0.00 + 0.025
n.links.loc[(n.links.index == 'transmission:GRIDREGION-JPN-CB~GRIDREGION-JPN-TK'), 'max_utilisation_rate'] = 0.25 + 0.025
n.links.loc[(n.links.index == 'transmission:GRIDREGION-JPN-CB~GRIDREGION-JPN-HR'), 'max_utilisation_rate'] = 0.02 + 0.025
n.links.loc[(n.links.index == 'transmission:GRIDREGION-JPN-CB~GRIDREGION-JPN-KA'), 'max_utilisation_rate'] = 0.04 + 0.025
n.links.loc[(n.links.index == 'transmission:GRIDREGION-JPN-HR~GRIDREGION-JPN-CB'), 'max_utilisation_rate'] = 0.33 + 0.025
n.links.loc[(n.links.index == 'transmission:GRIDREGION-JPN-HR~GRIDREGION-JPN-KA'), 'max_utilisation_rate'] = 0.18 + 0.025
n.links.loc[(n.links.index == 'transmission:GRIDREGION-JPN-KA~GRIDREGION-JPN-HR'), 'max_utilisation_rate'] = 0.09 + 0.025
n.links.loc[(n.links.index == 'transmission:GRIDREGION-JPN-KA~GRIDREGION-JPN-CB'), 'max_utilisation_rate'] = 0.25 + 0.025
n.links.loc[(n.links.index == 'transmission:GRIDREGION-JPN-KA~GRIDREGION-JPN-CG'), 'max_utilisation_rate'] = 0.19 + 0.025
n.links.loc[(n.links.index == 'transmission:GRIDREGION-JPN-KA~GRIDREGION-JPN-SH'), 'max_utilisation_rate'] = 0.00 + 0.025
n.links.loc[(n.links.index == 'transmission:GRIDREGION-JPN-CG~GRIDREGION-JPN-KA'), 'max_utilisation_rate'] = 0.40 + 0.025
n.links.loc[(n.links.index == 'transmission:GRIDREGION-JPN-CG~GRIDREGION-JPN-SH'), 'max_utilisation_rate'] = 0.00 + 0.025
n.links.loc[(n.links.index == 'transmission:GRIDREGION-JPN-SH~GRIDREGION-JPN-KY'), 'max_utilisation_rate'] = 0.00 + 0.025
n.links.loc[(n.links.index == 'transmission:GRIDREGION-JPN-KY~GRIDREGION-JPN-CG'), 'max_utilisation_rate'] = 0.34 + 0.025
n.links.loc[(n.links.index == 'transmission:GRIDREGION-JPN-KY~GRIDREGION-JPN-SH'), 'max_utilisation_rate'] = 0.83 + 0.025

In [24]:
# min_utilisation_rate - transmission
n.links.loc[(n.links.index == 'transmission:GRIDREGION-JPN-HK~GRIDREGION-JPN-TH'), 'min_utilisation_rate'] = 0.48
n.links.loc[(n.links.index == 'transmission:GRIDREGION-JPN-TH~GRIDREGION-JPN-TK'), 'min_utilisation_rate'] = 0.5875
n.links.loc[(n.links.index == 'transmission:GRIDREGION-JPN-TK~GRIDREGION-JPN-CB'), 'min_utilisation_rate'] = 0.44
n.links.loc[(n.links.index == 'transmission:GRIDREGION-JPN-CB~GRIDREGION-JPN-TK'), 'min_utilisation_rate'] = 0.25
n.links.loc[(n.links.index == 'transmission:GRIDREGION-JPN-CB~GRIDREGION-JPN-KA'), 'min_utilisation_rate'] = 0.04
n.links.loc[(n.links.index == 'transmission:GRIDREGION-JPN-HR~GRIDREGION-JPN-CB'), 'min_utilisation_rate'] = 0.32
n.links.loc[(n.links.index == 'transmission:GRIDREGION-JPN-KA~GRIDREGION-JPN-CB'), 'min_utilisation_rate'] = 0.25
n.links.loc[(n.links.index == 'transmission:GRIDREGION-JPN-KA~GRIDREGION-JPN-HR'), 'min_utilisation_rate'] = 0.09
n.links.loc[(n.links.index == 'transmission:GRIDREGION-JPN-KA~GRIDREGION-JPN-CG'), 'min_utilisation_rate'] = 0.19
n.links.loc[(n.links.index == 'transmission:GRIDREGION-JPN-CG~GRIDREGION-JPN-KA'), 'min_utilisation_rate'] = 0.40
n.links.loc[(n.links.index == 'transmission:GRIDREGION-JPN-CG~GRIDREGION-JPN-KY'), 'min_utilisation_rate'] = 0.19
n.links.loc[(n.links.index == 'transmission:GRIDREGION-JPN-SH~GRIDREGION-JPN-KA'), 'min_utilisation_rate'] = 0.98
n.links.loc[(n.links.index == 'transmission:GRIDREGION-JPN-SH~GRIDREGION-JPN-CG'), 'min_utilisation_rate'] = 0.91

In [25]:
# min_utilisation_rate - transmission
n.links.loc[(n.links.index == 'transmission:GRIDREGION-JPN-HK~GRIDREGION-JPN-TH'), 'min_utilisation_rate'] = 0.48 - 0.025
n.links.loc[(n.links.index == 'transmission:GRIDREGION-JPN-TH~GRIDREGION-JPN-TK'), 'min_utilisation_rate'] = 0.5875 - 0.025
n.links.loc[(n.links.index == 'transmission:GRIDREGION-JPN-TK~GRIDREGION-JPN-CB'), 'min_utilisation_rate'] = 0.44 - 0.025
n.links.loc[(n.links.index == 'transmission:GRIDREGION-JPN-CB~GRIDREGION-JPN-TK'), 'min_utilisation_rate'] = 0.25 - 0.025
n.links.loc[(n.links.index == 'transmission:GRIDREGION-JPN-CB~GRIDREGION-JPN-KA'), 'min_utilisation_rate'] = 0.04 - 0.025
n.links.loc[(n.links.index == 'transmission:GRIDREGION-JPN-HR~GRIDREGION-JPN-CB'), 'min_utilisation_rate'] = 0.32 - 0.025
n.links.loc[(n.links.index == 'transmission:GRIDREGION-JPN-KA~GRIDREGION-JPN-CB'), 'min_utilisation_rate'] = 0.25 - 0.025
n.links.loc[(n.links.index == 'transmission:GRIDREGION-JPN-KA~GRIDREGION-JPN-HR'), 'min_utilisation_rate'] = 0.09 - 0.025
n.links.loc[(n.links.index == 'transmission:GRIDREGION-JPN-KA~GRIDREGION-JPN-CG'), 'min_utilisation_rate'] = 0.19 - 0.025
n.links.loc[(n.links.index == 'transmission:GRIDREGION-JPN-CG~GRIDREGION-JPN-KA'), 'min_utilisation_rate'] = 0.40 - 0.025
n.links.loc[(n.links.index == 'transmission:GRIDREGION-JPN-CG~GRIDREGION-JPN-KY'), 'min_utilisation_rate'] = 0.19 - 0.025
n.links.loc[(n.links.index == 'transmission:GRIDREGION-JPN-SH~GRIDREGION-JPN-KA'), 'min_utilisation_rate'] = 0.98 - 0.025
n.links.loc[(n.links.index == 'transmission:GRIDREGION-JPN-SH~GRIDREGION-JPN-CG'), 'min_utilisation_rate'] = 0.91 - 0.025

In [26]:
# max_utilisation_rate
# hydro-pumped-storage
n.storage_units.loc[(n.storage_units.carrier == 'hydro-pumped-storage-unspecified') & (n.storage_units.bus == 'GRIDREGION-JPN-HK'), 'discharge_min_utilisation_rate'] = 0.126
n.storage_units.loc[(n.storage_units.carrier == 'hydro-pumped-storage-unspecified') & (n.storage_units.bus == 'GRIDREGION-JPN-HK'), 'charge_max_utilisation_rate'] = 0.180

n.storage_units.loc[(n.storage_units.carrier == 'hydro-pumped-storage-unspecified') & (n.storage_units.bus == 'GRIDREGION-JPN-TH'), 'discharge_min_utilisation_rate'] = 0.136
n.storage_units.loc[(n.storage_units.carrier == 'hydro-pumped-storage-unspecified') & (n.storage_units.bus == 'GRIDREGION-JPN-TH'), 'charge_max_utilisation_rate'] = 0.195

n.storage_units.loc[(n.storage_units.carrier == 'hydro-pumped-storage-unspecified') & (n.storage_units.bus == 'GRIDREGION-JPN-TK'), 'discharge_min_utilisation_rate'] = 0.121
n.storage_units.loc[(n.storage_units.carrier == 'hydro-pumped-storage-unspecified') & (n.storage_units.bus == 'GRIDREGION-JPN-TK'), 'charge_max_utilisation_rate'] = 0.174

n.storage_units.loc[(n.storage_units.carrier == 'hydro-pumped-storage-unspecified') & (n.storage_units.bus == 'GRIDREGION-JPN-CB'), 'discharge_min_utilisation_rate'] = 0.059
n.storage_units.loc[(n.storage_units.carrier == 'hydro-pumped-storage-unspecified') & (n.storage_units.bus == 'GRIDREGION-JPN-CB'), 'charge_max_utilisation_rate'] = 0.085

n.storage_units.loc[(n.storage_units.carrier == 'hydro-pumped-storage-unspecified') & (n.storage_units.bus == 'GRIDREGION-JPN-HR'), 'discharge_min_utilisation_rate'] = 0.055
n.storage_units.loc[(n.storage_units.carrier == 'hydro-pumped-storage-unspecified') & (n.storage_units.bus == 'GRIDREGION-JPN-HR'), 'charge_max_utilisation_rate'] = 0.080

n.storage_units.loc[(n.storage_units.carrier == 'hydro-pumped-storage-unspecified') & (n.storage_units.bus == 'GRIDREGION-JPN-KA'), 'discharge_min_utilisation_rate'] = 0.056
n.storage_units.loc[(n.storage_units.carrier == 'hydro-pumped-storage-unspecified') & (n.storage_units.bus == 'GRIDREGION-JPN-KA'), 'charge_max_utilisation_rate'] = 0.080

n.storage_units.loc[(n.storage_units.carrier == 'hydro-pumped-storage-unspecified') & (n.storage_units.bus == 'GRIDREGION-JPN-CG'), 'discharge_min_utilisation_rate'] = 0.056
n.storage_units.loc[(n.storage_units.carrier == 'hydro-pumped-storage-unspecified') & (n.storage_units.bus == 'GRIDREGION-JPN-CG'), 'charge_max_utilisation_rate'] = 0.081

n.storage_units.loc[(n.storage_units.carrier == 'hydro-pumped-storage-unspecified') & (n.storage_units.bus == 'GRIDREGION-JPN-SH'), 'discharge_min_utilisation_rate'] = 0.064
n.storage_units.loc[(n.storage_units.carrier == 'hydro-pumped-storage-unspecified') & (n.storage_units.bus == 'GRIDREGION-JPN-SH'), 'charge_max_utilisation_rate'] = 0.092

n.storage_units.loc[(n.storage_units.carrier == 'hydro-pumped-storage-unspecified') & (n.storage_units.bus == 'GRIDREGION-JPN-KY'), 'discharge_min_utilisation_rate'] = 0.057
n.storage_units.loc[(n.storage_units.carrier == 'hydro-pumped-storage-unspecified') & (n.storage_units.bus == 'GRIDREGION-JPN-KY'), 'charge_max_utilisation_rate'] = 0.083

In [ ]:
n.generators.to_csv("generators.csv")
n.links.to_csv("links.csv")
n.storage_units.to_csv("storage.csv")

In [ ]:
ramping_costs = {
    'coal-subcritical': 299,
    'coal-supercritical': 264,
    'coal-ammonia-cofiring': 300,
    'gas-conventional': 365,
    'gas-combined-cycle': 209,
    'gas-advanced-combined-cycle': 178,
    'gas-more-advanced-combined-cycle': 173,
    'gas-hydrogen-cofiring': 173,
    'gas-ccs': 173
}

In [27]:
n.optimize.create_model()
# constr_max_annual_utilisation_generator(n, carriers='coal-unspecified|gas-unspecified') # Calibration
# constr_min_annual_utilisation_generator(n, carriers='coal-unspecified|gas-unspecified') # Calibration
constr_max_annual_utilisation_generator(n, carriers='coal|gas') # Set max annual utilisation for these generators
constr_min_annual_utilisation_generator(n, carriers='coal|gas') # Set min annual utilisation for these generators
constr_max_annual_utilisation_links(n, carriers='transmission') # Set max annual utilisation for these links
constr_min_annual_utilisation_links(n, carriers='transmission') # Set min annual utilisation for these links
constr_min_annual_utilisation_storage_discharge(n, carriers='hydro-pumped-storage-unspecified') # Set min annual utilisation for these storage units
constr_max_annual_utilisation_storage_charge(n, carriers='hydro-pumped-storage-unspecified') # Set min annual utilisation for these storage units
constr_soc_intraday_profile(
    n, 
    max_csv="/home/jy/tza-pypsa/ClientEarth/data/storage_profiles/state_of_charge_intraday_profile_annual_max.csv",
    min_csv="/home/jy/tza-pypsa/ClientEarth/data/storage_profiles/state_of_charge_intraday_profile_annual_min.csv"
)
constr_soc_weekly_profile(
    n, 
    max_csv="/home/jy/tza-pypsa/ClientEarth/data/storage_profiles/state_of_charge_weekly_profile_annual_max.csv",
    min_csv="/home/jy/tza-pypsa/ClientEarth/data/storage_profiles/state_of_charge_weekly_profile_annual_min.csv",
    day_shift=2
)
constr_production_target_min(n, 
                            ['GRIDREGION-JPN-SH', 'GRIDREGION-JPN-HR', 'GRIDREGION-JPN-CB', 
                            'GRIDREGION-JPN-HK', 'GRIDREGION-JPN-KA', 'GRIDREGION-JPN-CG', 
                            'GRIDREGION-JPN-TK', 'GRIDREGION-JPN-TH', 'GRIDREGION-JPN-KY'],
                            ['wind-offshore-unspecified','photovoltaic-unspecified', 'wind-onshore', 'geothermal-unspecified', 'biomass', 'hydro-reservoir-and-run-of-river'],
                            0.50)

constr_production_target_max(n, 
                            ['GRIDREGION-JPN-SH', 'GRIDREGION-JPN-HR', 'GRIDREGION-JPN-CB', 
                            'GRIDREGION-JPN-HK', 'GRIDREGION-JPN-KA', 'GRIDREGION-JPN-CG', 
                            'GRIDREGION-JPN-TK', 'GRIDREGION-JPN-TH', 'GRIDREGION-JPN-KY'],
                            ['wind-offshore-unspecified','photovoltaic-unspecified', 'wind-onshore', 'geothermal-unspecified', 'biomass', 'hydro-reservoir-and-run-of-river'],
                            0.505)

# apply_ramping_cost(n, ramping_costs)

WARNING:pypsa.consistency:The following generators have carriers which are not defined:
Index(['coal-subcritical:GRIDREGION-JPN-HK',
       'coal-subcritical:GRIDREGION-JPN-TH',
       'coal-subcritical:GRIDREGION-JPN-TK',
       'coal-subcritical:GRIDREGION-JPN-HR',
       'coal-subcritical:GRIDREGION-JPN-KA',
       'coal-subcritical:GRIDREGION-JPN-SH',
       'coal-subcritical:GRIDREGION-JPN-CG',
       'coal-subcritical:GRIDREGION-JPN-KY',
       'coal-supercritical:GRIDREGION-JPN-HK',
       'coal-supercritical:GRIDREGION-JPN-TH',
       'coal-supercritical:GRIDREGION-JPN-TK',
       'coal-supercritical:GRIDREGION-JPN-CB',
       'coal-supercritical:GRIDREGION-JPN-HR',
       'coal-supercritical:GRIDREGION-JPN-KA',
       'coal-supercritical:GRIDREGION-JPN-SH',
       'coal-supercritical:GRIDREGION-JPN-CG',
       'coal-supercritical:GRIDREGION-JPN-KY',
       'gas-advanced-combined-cycle:GRIDREGION-JPN-TH',
       'gas-advanced-combined-cycle:GRIDREGION-JPN-TK',
       'gas-advanced-combined-cycle:GRIDREGION-JPN-CB',
       'gas-advanced-combined-cycle:GRIDREGION-JPN-KA',
       'gas-advanced-combined-cycle:GRIDREGION-JPN-SH',
       'gas-advanced-combined-cycle:GRIDREGION-JPN-CG',
       'gas-combined-cycle:GRIDREGION-JPN-TH',
       'gas-combined-cycle:GRIDREGION-JPN-TK',
       'gas-combined-cycle:GRIDREGION-JPN-CB',
       'gas-combined-cycle:GRIDREGION-JPN-KA',
       'gas-combined-cycle:GRIDREGION-JPN-SH',
       'gas-combined-cycle:GRIDREGION-JPN-KY',
       'gas-conventional:GRIDREGION-JPN-HK',
       'gas-conventional:GRIDREGION-JPN-TH',
       'gas-conventional:GRIDREGION-JPN-TK',
       'gas-conventional:GRIDREGION-JPN-CB',
       'gas-conventional:GRIDREGION-JPN-HR',
       'gas-conventional:GRIDREGION-JPN-KA',
       'gas-conventional:GRIDREGION-JPN-SH',
       'gas-conventional:GRIDREGION-JPN-CG',
       'gas-conventional:GRIDREGION-JPN-KY',
       'gas-more-advanced-combined-cycle:GRIDREGION-JPN-HK',
       'gas-more-advanced-combined-cycle:GRIDREGION-JPN-TH',
       'gas-more-advanced-combined-cycle:GRIDREGION-JPN-TK',
       'gas-more-advanced-combined-cycle:GRIDREGION-JPN-CB',
       'gas-more-advanced-combined-cycle:GRIDREGION-JPN-HR',
       'gas-more-advanced-combined-cycle:GRIDREGION-JPN-KA',
       'gas-more-advanced-combined-cycle:GRIDREGION-JPN-CG',
       'gas-more-advanced-combined-cycle:GRIDREGION-JPN-KY'],
      dtype='object', name='Generator')

['gas-ccs:GRIDREGION-JPN-SH', 'gas-ccs:GRIDREGION-JPN-HR', 'gas-ccs:GRIDREGION-JPN-CB', 'gas-ccs:GRIDREGION-JPN-HK', 'gas-ccs:GRIDREGION-JPN-KA', 'gas-ccs:GRIDREGION-JPN-CG', 'gas-ccs:GRIDREGION-JPN-TK', 'gas-ccs:GRIDREGION-JPN-TH', 'gas-ccs:GRIDREGION-JPN-KY', 'coal-ammonia-cofiring:GRIDREGION-JPN-SH', 'coal-ammonia-cofiring:GRIDREGION-JPN-HR', 'coal-ammonia-cofiring:GRIDREGION-JPN-CB', 'coal-ammonia-cofiring:GRIDREGION-JPN-HK', 'coal-ammonia-cofiring:GRIDREGION-JPN-KA', 'coal-ammonia-cofiring:GRIDREGION-JPN-CG', 'coal-ammonia-cofiring:GRIDREGION-JPN-TK', 'coal-ammonia-cofiring:GRIDREGION-JPN-TH', 'coal-ammonia-cofiring:GRIDREGION-JPN-KY', 'gas-hydrogen-cofiring:GRIDREGION-JPN-SH', 'gas-hydrogen-cofiring:GRIDREGION-JPN-HR', 'gas-hydrogen-cofiring:GRIDREGION-JPN-CB', 'gas-hydrogen-cofiring:GRIDREGION-JPN-HK', 'gas-hydrogen-cofiring:GRIDREGION-JPN-KA', 'gas-hydrogen-cofiring:GRIDREGION-JPN-CG', 'gas-hydrogen-cofiring:GRIDREGION-JPN-TK', 'gas-hydrogen-cofiring:GRIDREGION-JPN-TH', 'gas-hydrogen-cofiring:GRIDREGION-JPN-KY', 'coal-subcritical:GRIDREGION-JPN-HK', 'coal-subcritical:GRIDREGION-JPN-TH', 'coal-subcritical:GRIDREGION-JPN-TK', 'coal-subcritical:GRIDREGION-JPN-HR', 'coal-subcritical:GRIDREGION-JPN-KA', 'coal-subcritical:GRIDREGION-JPN-SH', 'coal-subcritical:GRIDREGION-JPN-CG', 'coal-subcritical:GRIDREGION-JPN-KY', 'coal-supercritical:GRIDREGION-JPN-HK', 'coal-supercritical:GRIDREGION-JPN-TH', 'coal-supercritical:GRIDREGION-JPN-TK', 'coal-supercritical:GRIDREGION-JPN-CB', 'coal-supercritical:GRIDREGION-JPN-HR', 'coal-supercritical:GRIDREGION-JPN-KA', 'coal-supercritical:GRIDREGION-JPN-SH', 'coal-supercritical:GRIDREGION-JPN-CG', 'coal-supercritical:GRIDREGION-JPN-KY', 'gas-advanced-combined-cycle:GRIDREGION-JPN-TH', 'gas-advanced-combined-cycle:GRIDREGION-JPN-TK', 'gas-advanced-combined-cycle:GRIDREGION-JPN-CB', 'gas-advanced-combined-cycle:GRIDREGION-JPN-KA', 'gas-advanced-combined-cycle:GRIDREGION-JPN-SH', 'gas-advanced-combined-cycle:GRIDREGION-JPN-CG', 'gas-combined-cycle:GRIDREGION-JPN-TH', 'gas-combined-cycle:GRIDREGION-JPN-TK', 'gas-combined-cycle:GRIDREGION-JPN-CB', 'gas-combined-cycle:GRIDREGION-JPN-KA', 'gas-combined-cycle:GRIDREGION-JPN-SH', 'gas-combined-cycle:GRIDREGION-JPN-KY', 'gas-conventional:GRIDREGION-JPN-HK', 'gas-conventional:GRIDREGION-JPN-TH', 'gas-conventional:GRIDREGION-JPN-TK', 'gas-conventional:GRIDREGION-JPN-CB', 'gas-conventional:GRIDREGION-JPN-HR', 'gas-conventional:GRIDREGION-JPN-KA', 'gas-conventional:GRIDREGION-JPN-SH', 'gas-conventional:GRIDREGION-JPN-CG', 'gas-conventional:GRIDREGION-JPN-KY', 'gas-more-advanced-combined-cycle:GRIDREGION-JPN-HK', 'gas-more-advanced-combined-cycle:GRIDREGION-JPN-TH', 'gas-more-advanced-combined-cycle:GRIDREGION-JPN-TK', 'gas-more-advanced-combined-cycle:GRIDREGION-JPN-CB', 'gas-more-advanced-combined-cycle:GRIDREGION-JPN-HR', 'gas-more-advanced-combined-cycle:GRIDREGION-JPN-KA', 'gas-more-advanced-combined-cycle:GRIDREGION-JPN-CG', 'gas-more-advanced-combined-cycle:GRIDREGION-JPN-KY']
['gas-ccs:GRIDREGION-JPN-SH', 'gas-ccs:GRIDREGION-JPN-HR', 'gas-ccs:GRIDREGION-JPN-CB', 'gas-ccs:GRIDREGION-JPN-HK', 'gas-ccs:GRIDREGION-JPN-KA', 'gas-ccs:GRIDREGION-JPN-CG', 'gas-ccs:GRIDREGION-JPN-TK', 'gas-ccs:GRIDREGION-JPN-TH', 'gas-ccs:GRIDREGION-JPN-KY', 'coal-ammonia-cofiring:GRIDREGION-JPN-HK', 'coal-ammonia-cofiring:GRIDREGION-JPN-TK', 'coal-ammonia-cofiring:GRIDREGION-JPN-TH', 'coal-ammonia-cofiring:GRIDREGION-JPN-KY', 'gas-hydrogen-cofiring:GRIDREGION-JPN-SH', 'gas-hydrogen-cofiring:GRIDREGION-JPN-HR', 'gas-hydrogen-cofiring:GRIDREGION-JPN-CB', 'gas-hydrogen-cofiring:GRIDREGION-JPN-HK', 'gas-hydrogen-cofiring:GRIDREGION-JPN-KA', 'gas-hydrogen-cofiring:GRIDREGION-JPN-CG', 'gas-hydrogen-cofiring:GRIDREGION-JPN-TK', 'gas-hydrogen-cofiring:GRIDREGION-JPN-TH', 'gas-hydrogen-cofiring:GRIDREGION-JPN-KY', 'coal-subcritical:GRIDREGION-JPN-HK', 'coal-subcritical:GRIDREGION-JPN-TH', 'coal-subcritical:GRIDREGION-JPN-TK', 'coal-subcritical:GRIDREGION-JPN-KY', 'coal-supercritical:GRIDREGION-JPN-HK', 'coal-supercritical:GRIDREGION-JPN-TH', 'coal-supercritical:GRIDREGION-JPN-TK', 'coal-supercritical:GRIDREGION-JPN-KY', 'gas-advanced-combined-cycle:GRIDREGION-JPN-TH', 'gas-advanced-combined-cycle:GRIDREGION-JPN-TK', 'gas-advanced-combined-cycle:GRIDREGION-JPN-CB', 'gas-advanced-combined-cycle:GRIDREGION-JPN-KA', 'gas-advanced-combined-cycle:GRIDREGION-JPN-SH', 'gas-advanced-combined-cycle:GRIDREGION-JPN-CG', 'gas-combined-cycle:GRIDREGION-JPN-TH', 'gas-combined-cycle:GRIDREGION-JPN-TK', 'gas-combined-cycle:GRIDREGION-JPN-CB', 'gas-combined-cycle:GRIDREGION-JPN-KA', 'gas-combined-cycle:GRIDREGION-JPN-SH', 'gas-combined-cycle:GRIDREGION-JPN-KY', 'gas-conventional:GRIDREGION-JPN-HK', 'gas-conventional:GRIDREGION-JPN-TH', 'gas-conventional:GRIDREGION-JPN-TK', 'gas-conventional:GRIDREGION-JPN-CB', 'gas-conventional:GRIDREGION-JPN-HR', 'gas-conventional:GRIDREGION-JPN-KA', 'gas-conventional:GRIDREGION-JPN-SH', 'gas-conventional:GRIDREGION-JPN-CG', 'gas-conventional:GRIDREGION-JPN-KY', 'gas-more-advanced-combined-cycle:GRIDREGION-JPN-HK', 'gas-more-advanced-combined-cycle:GRIDREGION-JPN-TH', 'gas-more-advanced-combined-cycle:GRIDREGION-JPN-TK', 'gas-more-advanced-combined-cycle:GRIDREGION-JPN-CB', 'gas-more-advanced-combined-cycle:GRIDREGION-JPN-HR', 'gas-more-advanced-combined-cycle:GRIDREGION-JPN-KA', 'gas-more-advanced-combined-cycle:GRIDREGION-JPN-CG', 'gas-more-advanced-combined-cycle:GRIDREGION-JPN-KY']
['transmission:GRIDREGION-JPN-KY~GRIDREGION-JPN-SH', 'transmission:GRIDREGION-JPN-SH~GRIDREGION-JPN-KY', 'transmission:GRIDREGION-JPN-KY~GRIDREGION-JPN-CG', 'transmission:GRIDREGION-JPN-HK~GRIDREGION-JPN-TH', 'transmission:GRIDREGION-JPN-KA~GRIDREGION-JPN-CG', 'transmission:GRIDREGION-JPN-CB~GRIDREGION-JPN-HR', 'transmission:GRIDREGION-JPN-KA~GRIDREGION-JPN-HR', 'transmission:GRIDREGION-JPN-KA~GRIDREGION-JPN-SH', 'transmission:GRIDREGION-JPN-KA~GRIDREGION-JPN-CB', 'transmission:GRIDREGION-JPN-TK~GRIDREGION-JPN-TH', 'transmission:GRIDREGION-JPN-HR~GRIDREGION-JPN-CB', 'transmission:GRIDREGION-JPN-TH~GRIDREGION-JPN-HK', 'transmission:GRIDREGION-JPN-CG~GRIDREGION-JPN-KA', 'transmission:GRIDREGION-JPN-HR~GRIDREGION-JPN-KA', 'transmission:GRIDREGION-JPN-TH~GRIDREGION-JPN-TK', 'transmission:GRIDREGION-JPN-CG~GRIDREGION-JPN-SH', 'transmission:GRIDREGION-JPN-TK~GRIDREGION-JPN-CB', 'transmission:GRIDREGION-JPN-CB~GRIDREGION-JPN-KA', 'transmission:GRIDREGION-JPN-CB~GRIDREGION-JPN-TK']
['transmission:GRIDREGION-JPN-HK~GRIDREGION-JPN-TH', 'transmission:GRIDREGION-JPN-KA~GRIDREGION-JPN-CG', 'transmission:GRIDREGION-JPN-KA~GRIDREGION-JPN-HR', 'transmission:GRIDREGION-JPN-KA~GRIDREGION-JPN-CB', 'transmission:GRIDREGION-JPN-SH~GRIDREGION-JPN-KA', 'transmission:GRIDREGION-JPN-HR~GRIDREGION-JPN-CB', 'transmission:GRIDREGION-JPN-CG~GRIDREGION-JPN-KY', 'transmission:GRIDREGION-JPN-CG~GRIDREGION-JPN-KA', 'transmission:GRIDREGION-JPN-SH~GRIDREGION-JPN-CG', 'transmission:GRIDREGION-JPN-TH~GRIDREGION-JPN-TK', 'transmission:GRIDREGION-JPN-TK~GRIDREGION-JPN-CB', 'transmission:GRIDREGION-JPN-CB~GRIDREGION-JPN-KA', 'transmission:GRIDREGION-JPN-CB~GRIDREGION-JPN-TK']
['hydro-pumped-storage-unspecified:GRIDREGION-JPN-SH', 'hydro-pumped-storage-unspecified:GRIDREGION-JPN-HR', 'hydro-pumped-storage-unspecified:GRIDREGION-JPN-CB', 'hydro-pumped-storage-unspecified:GRIDREGION-JPN-HK', 'hydro-pumped-storage-unspecified:GRIDREGION-JPN-KA', 'hydro-pumped-storage-unspecified:GRIDREGION-JPN-CG', 'hydro-pumped-storage-unspecified:GRIDREGION-JPN-TK', 'hydro-pumped-storage-unspecified:GRIDREGION-JPN-TH', 'hydro-pumped-storage-unspecified:GRIDREGION-JPN-KY']
['hydro-pumped-storage-unspecified:GRIDREGION-JPN-SH', 'hydro-pumped-storage-unspecified:GRIDREGION-JPN-HR', 'hydro-pumped-storage-unspecified:GRIDREGION-JPN-CB', 'hydro-pumped-storage-unspecified:GRIDREGION-JPN-HK', 'hydro-pumped-storage-unspecified:GRIDREGION-JPN-KA', 'hydro-pumped-storage-unspecified:GRIDREGION-JPN-CG', 'hydro-pumped-storage-unspecified:GRIDREGION-JPN-TK', 'hydro-pumped-storage-unspecified:GRIDREGION-JPN-TH', 'hydro-pumped-storage-unspecified:GRIDREGION-JPN-KY']
Loaded SOC bounds for 9 units and 24 hour.
Intraday SOC constraints added for 9 units.
Loaded SOC bounds for 9 units and 7 dayofweek.
Weekly SOC constraints added for 9 units.
Added production target min constraint: wind-offshore-unspecified|photovoltaic-unspecified|wind-onshore|geothermal-unspecified|biomass|hydro-reservoir-and-run-of-river >= 50.0% in GRIDREGION-JPN-SH|GRIDREGION-JPN-HR|GRIDREGION-JPN-CB|GRIDREGION-JPN-HK|GRIDREGION-JPN-KA|GRIDREGION-JPN-CG|GRIDREGION-JPN-TK|GRIDREGION-JPN-TH|GRIDREGION-JPN-KY
Added production target max constraint: wind-offshore-unspecified|photovoltaic-unspecified|wind-onshore|geothermal-unspecified|biomass|hydro-reservoir-and-run-of-river <= 50.5% in GRIDREGION-JPN-SH|GRIDREGION-JPN-HR|GRIDREGION-JPN-CB|GRIDREGION-JPN-HK|GRIDREGION-JPN-KA|GRIDREGION-JPN-CG|GRIDREGION-JPN-TK|GRIDREGION-JPN-TH|GRIDREGION-JPN-KY

In [28]:
n.optimize.solve_model(
    solver_name='gurobi',
    solver_options={
        'threads': 8,
        'method': 2, # barrier
        'crossover': 0,
        'BarConvTol': 1.e-6,
        'Seed': 123,
        'AggFill': 0,
        'PreDual': 0,
        'LogFile': 'gurobi.log',
        'LogToConsole': 1  
    },
    io_api="direct",
    env=None,
)

INFO:linopy.model: Solve problem using Gurobi solver
INFO:linopy.model:Solver options:
 - threads: 8
 - method: 2
 - crossover: 0
 - BarConvTol: 1e-06
 - Seed: 123
 - AggFill: 0
 - PreDual: 0
 - LogFile: gurobi.log
 - LogToConsole: 1

Set parameter WLSAccessID

INFO:gurobipy:Set parameter WLSAccessID

Set parameter WLSSecret

INFO:gurobipy:Set parameter WLSSecret

Set parameter LicenseID to value 2526863

INFO:gurobipy:Set parameter LicenseID to value 2526863

WLS license 2526863 - registered to TransitionZero

INFO:gurobipy:WLS license 2526863 - registered to TransitionZero

Set parameter Threads to value 8

INFO:gurobipy:Set parameter Threads to value 8

Set parameter Method to value 2

INFO:gurobipy:Set parameter Method to value 2

Set parameter Crossover to value 0

INFO:gurobipy:Set parameter Crossover to value 0

Set parameter BarConvTol to value 1e-06

INFO:gurobipy:Set parameter BarConvTol to value 1e-06

Set parameter Seed to value 123

INFO:gurobipy:Set parameter Seed to value 123

Set parameter AggFill to value 0

INFO:gurobipy:Set parameter AggFill to value 0

Set parameter PreDual to value 0

INFO:gurobipy:Set parameter PreDual to value 0

Set parameter LogFile to value "gurobi.log"

INFO:gurobipy:Set parameter LogFile to value "gurobi.log"

Set parameter LogToConsole to value 1

INFO:gurobipy:Set parameter LogToConsole to value 1

Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (linux64 - "Debian GNU/Linux 12 (bookworm)")

INFO:gurobipy:Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (linux64 - "Debian GNU/Linux 12 (bookworm)")

INFO:gurobipy:

CPU model: INTEL(R) XEON(R) PLATINUM 8581C CPU @ 2.30GHz, instruction set [SSE2|AVX|AVX2|AVX512]

INFO:gurobipy:CPU model: INTEL(R) XEON(R) PLATINUM 8581C CPU @ 2.30GHz, instruction set [SSE2|AVX|AVX2|AVX512]

Thread count: 8 physical cores, 16 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 8 physical cores, 16 logical processors, using up to 8 threads

INFO:gurobipy:

Non-default parameters:

INFO:gurobipy:Non-default parameters:

Method  2

INFO:gurobipy:Method  2

BarConvTol  1e-06

INFO:gurobipy:BarConvTol  1e-06

Crossover  0

INFO:gurobipy:Crossover  0

AggFill  0

INFO:gurobipy:AggFill  0

PreDual  0

INFO:gurobipy:PreDual  0

Seed  123

INFO:gurobipy:Seed  123

Threads  8

INFO:gurobipy:Threads  8

INFO:gurobipy:

WLS license 2526863 - registered to TransitionZero

INFO:gurobipy:WLS license 2526863 - registered to TransitionZero

Optimize a model with 5388059 rows, 1857166 columns and 13881827 nonzeros

INFO:gurobipy:Optimize a model with 5388059 rows, 1857166 columns and 13881827 nonzeros

Model fingerprint: 0x339266d7

INFO:gurobipy:Model fingerprint: 0x339266d7

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [1e-02, 6e+00]

INFO:gurobipy:  Matrix range     [1e-02, 6e+00]

  Objective range  [1e+00, 5e+05]

INFO:gurobipy:  Objective range  [1e+00, 5e+05]

  Bounds range     [2e+10, 2e+10]

INFO:gurobipy:  Bounds range     [2e+10, 2e+10]

  RHS range        [4e+00, 1e+08]

INFO:gurobipy:  RHS range        [4e+00, 1e+08]

Warning: Model contains large bounds

INFO:gurobipy:Warning: Model contains large bounds

         Consider reformulating model or setting NumericFocus parameter

INFO:gurobipy:         Consider reformulating model or setting NumericFocus parameter

         to avoid numerical issues.

INFO:gurobipy:         to avoid numerical issues.

Presolve removed 3824388 rows and 540000 columns (presolve time = 5s)...

INFO:gurobipy:Presolve removed 3824388 rows and 540000 columns (presolve time = 5s)...

Presolve removed 3838802 rows and 554414 columns (presolve time = 10s)...

INFO:gurobipy:Presolve removed 3838802 rows and 554414 columns (presolve time = 10s)...

Presolve removed 4285831 rows and 554414 columns

INFO:gurobipy:Presolve removed 4285831 rows and 554414 columns

Presolve time: 11.80s

INFO:gurobipy:Presolve time: 11.80s

Presolved: 1102228 rows, 1749781 columns, 6366177 nonzeros

INFO:gurobipy:Presolved: 1102228 rows, 1749781 columns, 6366177 nonzeros

Ordering time: 5.91s

INFO:gurobipy:Ordering time: 5.91s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 Dense cols : 38

INFO:gurobipy: Dense cols : 38

 AA' NZ     : 6.033e+06

INFO:gurobipy: AA' NZ     : 6.033e+06

 Factor NZ  : 4.236e+07 (roughly 1.5 GB of memory)

INFO:gurobipy: Factor NZ  : 4.236e+07 (roughly 1.5 GB of memory)

 Factor Ops : 1.059e+10 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.059e+10 (less than 1 second per iteration)

 Threads    : 8

INFO:gurobipy: Threads    : 8

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   1.18919776e+15 -1.34671201e+15  6.48e+10 5.26e+02  1.53e+12    20s

INFO:gurobipy:   0   1.18919776e+15 -1.34671201e+15  6.48e+10 5.26e+02  1.53e+12    20s

   1   1.18348504e+15 -1.45985523e+15  6.31e+10 9.04e+04  1.38e+12    21s

INFO:gurobipy:   1   1.18348504e+15 -1.45985523e+15  6.31e+10 9.04e+04  1.38e+12    21s

   2   1.12767981e+15 -1.47261290e+15  4.64e+10 7.60e+04  1.03e+12    21s

INFO:gurobipy:   2   1.12767981e+15 -1.47261290e+15  4.64e+10 7.60e+04  1.03e+12    21s

   3   6.34602316e+14 -1.47969580e+15  3.19e+10 5.76e+04  7.20e+11    22s

INFO:gurobipy:   3   6.34602316e+14 -1.47969580e+15  3.19e+10 5.76e+04  7.20e+11    22s

   4   4.93921939e+14 -1.48175884e+15  2.32e+10 3.81e+04  5.27e+11    23s

INFO:gurobipy:   4   4.93921939e+14 -1.48175884e+15  2.32e+10 3.81e+04  5.27e+11    23s

   5   1.16051533e+14 -1.45327555e+15  4.33e+09 5.12e+03  9.90e+10    24s

INFO:gurobipy:   5   1.16051533e+14 -1.45327555e+15  4.33e+09 5.12e+03  9.90e+10    24s

   6   3.18355505e+13 -1.36193943e+15  7.31e+08 1.32e+03  1.78e+10    26s

INFO:gurobipy:   6   3.18355505e+13 -1.36193943e+15  7.31e+08 1.32e+03  1.78e+10    26s

   7   1.60866782e+13 -1.04143555e+15  9.49e+07 1.32e+02  2.53e+09    27s

INFO:gurobipy:   7   1.60866782e+13 -1.04143555e+15  9.49e+07 1.32e+02  2.53e+09    27s

   8   1.48802866e+13 -4.80974230e+14  5.29e+07 9.43e+00  1.28e+09    28s

INFO:gurobipy:   8   1.48802866e+13 -4.80974230e+14  5.29e+07 9.43e+00  1.28e+09    28s

   9   1.31518052e+13 -4.02027635e+14  2.68e+07 4.63e+00  6.85e+08    28s

INFO:gurobipy:   9   1.31518052e+13 -4.02027635e+14  2.68e+07 4.63e+00  6.85e+08    28s

  10   1.08144357e+13 -2.68149493e+14  1.36e+07 9.01e-06  3.50e+08    29s

INFO:gurobipy:  10   1.08144357e+13 -2.68149493e+14  1.36e+07 9.01e-06  3.50e+08    29s

  11   8.47060225e+12 -2.15990681e+14  8.85e+06 1.22e-05  2.33e+08    29s

INFO:gurobipy:  11   8.47060225e+12 -2.15990681e+14  8.85e+06 1.22e-05  2.33e+08    29s

  12   6.81849324e+12 -1.56044688e+14  5.38e+06 1.23e-05  1.42e+08    30s

INFO:gurobipy:  12   6.81849324e+12 -1.56044688e+14  5.38e+06 1.23e-05  1.42e+08    30s

  13   3.74816985e+12 -1.01646153e+14  2.01e+06 9.43e-06  6.30e+07    31s

INFO:gurobipy:  13   3.74816985e+12 -1.01646153e+14  2.01e+06 9.43e-06  6.30e+07    31s

  14   2.44239098e+12 -9.02157488e+13  1.09e+06 1.31e-05  4.43e+07    31s

INFO:gurobipy:  14   2.44239098e+12 -9.02157488e+13  1.09e+06 1.31e-05  4.43e+07    31s

  15   1.49180342e+12 -5.55567288e+13  4.86e+05 1.67e-05  2.37e+07    32s

INFO:gurobipy:  15   1.49180342e+12 -5.55567288e+13  4.86e+05 1.67e-05  2.37e+07    32s

  16   1.16091208e+12 -3.22103266e+13  3.30e+05 4.73e-05  1.38e+07    32s

INFO:gurobipy:  16   1.16091208e+12 -3.22103266e+13  3.30e+05 4.73e-05  1.38e+07    32s

  17   1.11901459e+12 -2.73697817e+13  3.11e+05 2.46e-05  1.19e+07    33s

INFO:gurobipy:  17   1.11901459e+12 -2.73697817e+13  3.11e+05 2.46e-05  1.19e+07    33s

  18   9.94425926e+11 -1.94776085e+13  2.49e+05 3.79e-05  8.58e+06    34s

INFO:gurobipy:  18   9.94425926e+11 -1.94776085e+13  2.49e+05 3.79e-05  8.58e+06    34s

  19   7.39249627e+11 -1.64175851e+13  1.38e+05 8.61e-05  6.68e+06    34s

INFO:gurobipy:  19   7.39249627e+11 -1.64175851e+13  1.38e+05 8.61e-05  6.68e+06    34s

  20   4.46808011e+11 -7.92575070e+12  5.04e+04 9.07e-05  2.97e+06    35s

INFO:gurobipy:  20   4.46808011e+11 -7.92575070e+12  5.04e+04 9.07e-05  2.97e+06    35s

  21   1.68219867e+11 -6.34739838e+12  8.76e+03 7.62e-05  1.95e+06    36s

INFO:gurobipy:  21   1.68219867e+11 -6.34739838e+12  8.76e+03 7.62e-05  1.95e+06    36s

  22   1.49408064e+11 -3.28973954e+12  4.31e+03 3.40e-05  1.01e+06    37s

INFO:gurobipy:  22   1.49408064e+11 -3.28973954e+12  4.31e+03 3.40e-05  1.01e+06    37s

  23   1.30130509e+11 -1.73819173e+12  3.05e+03 1.57e-05  5.43e+05    38s

INFO:gurobipy:  23   1.30130509e+11 -1.73819173e+12  3.05e+03 1.57e-05  5.43e+05    38s

  24   1.17631189e+11 -1.52464370e+12  2.35e+03 1.49e-05  4.76e+05    38s

INFO:gurobipy:  24   1.17631189e+11 -1.52464370e+12  2.35e+03 1.49e-05  4.76e+05    38s

  25   1.07516908e+11 -1.07647258e+12  1.82e+03 1.03e-05  3.42e+05    39s

INFO:gurobipy:  25   1.07516908e+11 -1.07647258e+12  1.82e+03 1.03e-05  3.42e+05    39s

  26   1.01282985e+11 -9.06300294e+11  1.50e+03 8.18e-06  2.90e+05    39s

INFO:gurobipy:  26   1.01282985e+11 -9.06300294e+11  1.50e+03 8.18e-06  2.90e+05    39s

  27   9.63261266e+10 -6.35712485e+11  1.26e+03 5.90e-06  2.11e+05    40s

INFO:gurobipy:  27   9.63261266e+10 -6.35712485e+11  1.26e+03 5.90e-06  2.11e+05    40s

  28   9.11132463e+10 -4.27475467e+11  1.03e+03 4.35e-06  1.49e+05    41s

INFO:gurobipy:  28   9.11132463e+10 -4.27475467e+11  1.03e+03 4.35e-06  1.49e+05    41s

  29   8.36174419e+10 -2.79025437e+11  7.22e+02 2.93e-06  1.04e+05    43s

INFO:gurobipy:  29   8.36174419e+10 -2.79025437e+11  7.22e+02 2.93e-06  1.04e+05    43s

  30   8.01734755e+10 -1.94934200e+11  5.88e+02 2.28e-06  7.89e+04    44s

INFO:gurobipy:  30   8.01734755e+10 -1.94934200e+11  5.88e+02 2.28e-06  7.89e+04    44s

  31   7.70828508e+10 -1.28552721e+11  4.58e+02 1.68e-06  5.89e+04    45s

INFO:gurobipy:  31   7.70828508e+10 -1.28552721e+11  4.58e+02 1.68e-06  5.89e+04    45s

  32   7.48388031e+10 -9.66171109e+10  3.58e+02 1.38e-06  4.91e+04    47s

INFO:gurobipy:  32   7.48388031e+10 -9.66171109e+10  3.58e+02 1.38e-06  4.91e+04    47s

  33   7.39182360e+10 -8.02544318e+10  3.17e+02 1.27e-06  4.41e+04    48s

INFO:gurobipy:  33   7.39182360e+10 -8.02544318e+10  3.17e+02 1.27e-06  4.41e+04    48s

  34   7.28611869e+10 -6.54135558e+10  2.66e+02 1.16e-06  3.96e+04    49s

INFO:gurobipy:  34   7.28611869e+10 -6.54135558e+10  2.66e+02 1.16e-06  3.96e+04    49s

  35   7.22385815e+10 -4.31275738e+10  2.33e+02 9.67e-07  3.30e+04    50s

INFO:gurobipy:  35   7.22385815e+10 -4.31275738e+10  2.33e+02 9.67e-07  3.30e+04    50s

  36   7.16199621e+10 -2.95028139e+10  1.91e+02 8.75e-07  2.89e+04    52s

INFO:gurobipy:  36   7.16199621e+10 -2.95028139e+10  1.91e+02 8.75e-07  2.89e+04    52s

  37   7.15543749e+10 -5.11801710e+09  1.57e+02 6.53e-07  2.19e+04    53s

INFO:gurobipy:  37   7.15543749e+10 -5.11801710e+09  1.57e+02 6.53e-07  2.19e+04    53s

  38   7.07793866e+10  1.65572025e+10  1.14e+02 4.57e-07  1.55e+04    54s

INFO:gurobipy:  38   7.07793866e+10  1.65572025e+10  1.14e+02 4.57e-07  1.55e+04    54s

  39   7.04576137e+10  2.87436002e+10  9.70e+01 3.59e-07  1.19e+04    55s

INFO:gurobipy:  39   7.04576137e+10  2.87436002e+10  9.70e+01 3.59e-07  1.19e+04    55s

  40   7.01096423e+10  3.53438701e+10  7.79e+01 3.03e-07  9.94e+03    57s

INFO:gurobipy:  40   7.01096423e+10  3.53438701e+10  7.79e+01 3.03e-07  9.94e+03    57s

  41   6.98973444e+10  4.29464588e+10  6.16e+01 2.37e-07  7.71e+03    58s

INFO:gurobipy:  41   6.98973444e+10  4.29464588e+10  6.16e+01 2.37e-07  7.71e+03    58s

  42   6.97783613e+10  5.19663317e+10  5.22e+01 1.39e-07  5.09e+03    59s

INFO:gurobipy:  42   6.97783613e+10  5.19663317e+10  5.22e+01 1.39e-07  5.09e+03    59s

  43   6.95907248e+10  5.70641972e+10  3.30e+01 1.02e-07  3.58e+03    61s

INFO:gurobipy:  43   6.95907248e+10  5.70641972e+10  3.30e+01 1.02e-07  3.58e+03    61s

  44   6.95296664e+10  6.33445085e+10  2.71e+01 4.28e-08  1.77e+03    62s

INFO:gurobipy:  44   6.95296664e+10  6.33445085e+10  2.71e+01 4.28e-08  1.77e+03    62s

  45   6.94570449e+10  6.43611038e+10  2.03e+01 5.77e-08  1.46e+03    63s

INFO:gurobipy:  45   6.94570449e+10  6.43611038e+10  2.03e+01 5.77e-08  1.46e+03    63s

  46   6.93473145e+10  6.47090310e+10  1.74e+01 5.77e-08  1.33e+03    64s

INFO:gurobipy:  46   6.93473145e+10  6.47090310e+10  1.74e+01 5.77e-08  1.33e+03    64s

  47   6.93035358e+10  6.54161332e+10  1.51e+01 7.08e-08  1.11e+03    65s

INFO:gurobipy:  47   6.93035358e+10  6.54161332e+10  1.51e+01 7.08e-08  1.11e+03    65s

  48   6.92423185e+10  6.61553745e+10  1.22e+01 5.31e-08  8.82e+02    67s

INFO:gurobipy:  48   6.92423185e+10  6.61553745e+10  1.22e+01 5.31e-08  8.82e+02    67s

  49   6.91759002e+10  6.65283955e+10  9.20e+00 7.54e-08  7.57e+02    68s

INFO:gurobipy:  49   6.91759002e+10  6.65283955e+10  9.20e+00 7.54e-08  7.57e+02    68s

  50   6.91387452e+10  6.70307219e+10  7.63e+00 1.12e-07  6.03e+02    69s

INFO:gurobipy:  50   6.91387452e+10  6.70307219e+10  7.63e+00 1.12e-07  6.03e+02    69s

  51   6.91352952e+10  6.71560490e+10  7.50e+00 1.15e-07  5.66e+02    70s

INFO:gurobipy:  51   6.91352952e+10  6.71560490e+10  7.50e+00 1.15e-07  5.66e+02    70s

  52   6.90531225e+10  6.75952788e+10  4.20e+00 1.15e-07  4.17e+02    72s

INFO:gurobipy:  52   6.90531225e+10  6.75952788e+10  4.20e+00 1.15e-07  4.17e+02    72s

  53   6.90358375e+10  6.78277688e+10  3.60e+00 1.15e-07  3.45e+02    73s

INFO:gurobipy:  53   6.90358375e+10  6.78277688e+10  3.60e+00 1.15e-07  3.45e+02    73s

  54   6.90177633e+10  6.82011730e+10  3.00e+00 2.26e-07  2.33e+02    74s

INFO:gurobipy:  54   6.90177633e+10  6.82011730e+10  3.00e+00 2.26e-07  2.33e+02    74s

  55   6.89955316e+10  6.82996520e+10  2.29e+00 5.43e-07  1.99e+02    75s

INFO:gurobipy:  55   6.89955316e+10  6.82996520e+10  2.29e+00 5.43e-07  1.99e+02    75s

  56   6.89729342e+10  6.84553493e+10  1.64e+00 9.64e-07  1.48e+02    77s

INFO:gurobipy:  56   6.89729342e+10  6.84553493e+10  1.64e+00 9.64e-07  1.48e+02    77s

  57   6.89629825e+10  6.85552390e+10  1.37e+00 1.50e-06  1.17e+02    78s

INFO:gurobipy:  57   6.89629825e+10  6.85552390e+10  1.37e+00 1.50e-06  1.17e+02    78s

  58   6.89514917e+10  6.86566533e+10  1.05e+00 1.91e-06  8.43e+01    79s

INFO:gurobipy:  58   6.89514917e+10  6.86566533e+10  1.05e+00 1.91e-06  8.43e+01    79s

  59   6.89444162e+10  6.86825474e+10  8.70e-01 1.95e-06  7.48e+01    80s

INFO:gurobipy:  59   6.89444162e+10  6.86825474e+10  8.70e-01 1.95e-06  7.48e+01    80s

  60   6.89412344e+10  6.87362919e+10  7.88e-01 9.02e-07  5.86e+01    82s

INFO:gurobipy:  60   6.89412344e+10  6.87362919e+10  7.88e-01 9.02e-07  5.86e+01    82s

  61   6.89325017e+10  6.87635285e+10  5.67e-01 1.89e-06  4.83e+01    83s

INFO:gurobipy:  61   6.89325017e+10  6.87635285e+10  5.67e-01 1.89e-06  4.83e+01    83s

  62   6.89292374e+10  6.87816095e+10  4.84e-01 2.36e-06  4.22e+01    84s

INFO:gurobipy:  62   6.89292374e+10  6.87816095e+10  4.84e-01 2.36e-06  4.22e+01    84s

  63   6.89257974e+10  6.88151363e+10  3.97e-01 2.30e-06  3.16e+01    85s

INFO:gurobipy:  63   6.89257974e+10  6.88151363e+10  3.97e-01 2.30e-06  3.16e+01    85s

  64   6.89226016e+10  6.88320607e+10  3.18e-01 1.80e-06  2.59e+01    87s

INFO:gurobipy:  64   6.89226016e+10  6.88320607e+10  3.18e-01 1.80e-06  2.59e+01    87s

  65   6.89204087e+10  6.88493682e+10  2.64e-01 1.45e-06  2.03e+01    88s

INFO:gurobipy:  65   6.89204087e+10  6.88493682e+10  2.64e-01 1.45e-06  2.03e+01    88s

  66   6.89177621e+10  6.88678791e+10  1.99e-01 4.35e-06  1.43e+01    89s

INFO:gurobipy:  66   6.89177621e+10  6.88678791e+10  1.99e-01 4.35e-06  1.43e+01    89s

  67   6.89147742e+10  6.88778276e+10  1.29e-01 8.36e-06  1.06e+01    91s

INFO:gurobipy:  67   6.89147742e+10  6.88778276e+10  1.29e-01 8.36e-06  1.06e+01    91s

  68   6.89128892e+10  6.88840161e+10  8.46e-02 1.04e-05  8.25e+00    92s

INFO:gurobipy:  68   6.89128892e+10  6.88840161e+10  8.46e-02 1.04e-05  8.25e+00    92s

  69   6.89123530e+10  6.88918967e+10  7.20e-02 7.61e-06  5.85e+00    93s

INFO:gurobipy:  69   6.89123530e+10  6.88918967e+10  7.20e-02 7.61e-06  5.85e+00    93s

  70   6.89111703e+10  6.88956416e+10  4.49e-02 1.15e-05  4.44e+00    94s

INFO:gurobipy:  70   6.89111703e+10  6.88956416e+10  4.49e-02 1.15e-05  4.44e+00    94s

  71   6.89107966e+10  6.88986490e+10  3.68e-02 1.05e-05  3.47e+00    96s

INFO:gurobipy:  71   6.89107966e+10  6.88986490e+10  3.68e-02 1.05e-05  3.47e+00    96s

  72   6.89105861e+10  6.89011872e+10  3.23e-02 1.84e-05  2.69e+00    97s

INFO:gurobipy:  72   6.89105861e+10  6.89011872e+10  3.23e-02 1.84e-05  2.69e+00    97s

  73   6.89101914e+10  6.89025184e+10  2.38e-02 2.42e-05  2.19e+00    98s

INFO:gurobipy:  73   6.89101914e+10  6.89025184e+10  2.38e-02 2.42e-05  2.19e+00    98s

  74   6.89099366e+10  6.89040319e+10  1.85e-02 1.89e-05  1.69e+00    99s

INFO:gurobipy:  74   6.89099366e+10  6.89040319e+10  1.85e-02 1.89e-05  1.69e+00    99s

  75   6.89098064e+10  6.89052881e+10  1.58e-02 2.99e-05  1.29e+00   101s

INFO:gurobipy:  75   6.89098064e+10  6.89052881e+10  1.58e-02 2.99e-05  1.29e+00   101s

  76   6.89095926e+10  6.89060417e+10  1.15e-02 2.24e-05  1.01e+00   102s

INFO:gurobipy:  76   6.89095926e+10  6.89060417e+10  1.15e-02 2.24e-05  1.01e+00   102s

  77   6.89095192e+10  6.89064771e+10  1.00e-02 2.67e-05  8.70e-01   103s

INFO:gurobipy:  77   6.89095192e+10  6.89064771e+10  1.00e-02 2.67e-05  8.70e-01   103s

  78   6.89094324e+10  6.89068436e+10  8.30e-03 3.10e-05  7.40e-01   105s

INFO:gurobipy:  78   6.89094324e+10  6.89068436e+10  8.30e-03 3.10e-05  7.40e-01   105s

  79   6.89093685e+10  6.89073058e+10  7.05e-03 5.84e-05  5.90e-01   106s

INFO:gurobipy:  79   6.89093685e+10  6.89073058e+10  7.05e-03 5.84e-05  5.90e-01   106s

  80   6.89093442e+10  6.89073945e+10  6.56e-03 5.89e-05  5.57e-01   107s

INFO:gurobipy:  80   6.89093442e+10  6.89073945e+10  6.56e-03 5.89e-05  5.57e-01   107s

  81   6.89093230e+10  6.89074504e+10  6.15e-03 5.87e-05  5.35e-01   108s

INFO:gurobipy:  81   6.89093230e+10  6.89074504e+10  6.15e-03 5.87e-05  5.35e-01   108s

  82   6.89092707e+10  6.89077845e+10  5.13e-03 5.68e-05  4.25e-01   110s

INFO:gurobipy:  82   6.89092707e+10  6.89077845e+10  5.13e-03 5.68e-05  4.25e-01   110s

  83   6.89092329e+10  6.89079658e+10  4.39e-03 7.40e-05  3.62e-01   111s

INFO:gurobipy:  83   6.89092329e+10  6.89079658e+10  4.39e-03 7.40e-05  3.62e-01   111s

  84   6.89092019e+10  6.89081295e+10  3.80e-03 8.19e-05  3.07e-01   112s

INFO:gurobipy:  84   6.89092019e+10  6.89081295e+10  3.80e-03 8.19e-05  3.07e-01   112s

  85   6.89091567e+10  6.89083269e+10  2.94e-03 6.89e-05  2.37e-01   113s

INFO:gurobipy:  85   6.89091567e+10  6.89083269e+10  2.94e-03 6.89e-05  2.37e-01   113s

  86   6.89091363e+10  6.89084725e+10  2.56e-03 5.69e-05  1.90e-01   115s

INFO:gurobipy:  86   6.89091363e+10  6.89084725e+10  2.56e-03 5.69e-05  1.90e-01   115s

  87   6.89091152e+10  6.89085725e+10  2.17e-03 4.45e-05  1.55e-01   116s

INFO:gurobipy:  87   6.89091152e+10  6.89085725e+10  2.17e-03 4.45e-05  1.55e-01   116s

  88   6.89090994e+10  6.89086459e+10  1.87e-03 3.92e-05  1.30e-01   117s

INFO:gurobipy:  88   6.89090994e+10  6.89086459e+10  1.87e-03 3.92e-05  1.30e-01   117s

  89   6.89090784e+10  6.89087045e+10  1.49e-03 3.28e-05  1.07e-01   119s

INFO:gurobipy:  89   6.89090784e+10  6.89087045e+10  1.49e-03 3.28e-05  1.07e-01   119s

  90   6.89090658e+10  6.89087453e+10  1.25e-03 3.25e-05  9.16e-02   120s

INFO:gurobipy:  90   6.89090658e+10  6.89087453e+10  1.25e-03 3.25e-05  9.16e-02   120s

  91   6.89090617e+10  6.89087616e+10  1.18e-03 3.05e-05  8.58e-02   121s

INFO:gurobipy:  91   6.89090617e+10  6.89087616e+10  1.18e-03 3.05e-05  8.58e-02   121s

  92   6.89090484e+10  6.89087922e+10  9.37e-04 2.65e-05  7.33e-02   123s

INFO:gurobipy:  92   6.89090484e+10  6.89087922e+10  9.37e-04 2.65e-05  7.33e-02   123s

  93   6.89090444e+10  6.89088038e+10  8.63e-04 2.50e-05  6.88e-02   124s

INFO:gurobipy:  93   6.89090444e+10  6.89088038e+10  8.63e-04 2.50e-05  6.88e-02   124s

  94   6.89090391e+10  6.89088201e+10  7.64e-04 2.28e-05  6.26e-02   125s

INFO:gurobipy:  94   6.89090391e+10  6.89088201e+10  7.64e-04 2.28e-05  6.26e-02   125s

  95   6.89090352e+10  6.89088465e+10  6.93e-04 1.93e-05  5.40e-02   127s

INFO:gurobipy:  95   6.89090352e+10  6.89088465e+10  6.93e-04 1.93e-05  5.40e-02   127s

  96   6.89090316e+10  6.89088687e+10  6.25e-04 1.65e-05  4.66e-02   128s

INFO:gurobipy:  96   6.89090316e+10  6.89088687e+10  6.25e-04 1.65e-05  4.66e-02   128s

  97   6.89090287e+10  6.89088781e+10  5.72e-04 1.53e-05  4.31e-02   129s

INFO:gurobipy:  97   6.89090287e+10  6.89088781e+10  5.72e-04 1.53e-05  4.31e-02   129s

  98   6.89090265e+10  6.89088902e+10  5.32e-04 1.52e-05  3.90e-02   130s

INFO:gurobipy:  98   6.89090265e+10  6.89088902e+10  5.32e-04 1.52e-05  3.90e-02   130s

  99   6.89090208e+10  6.89088982e+10  4.25e-04 1.40e-05  3.50e-02   131s

INFO:gurobipy:  99   6.89090208e+10  6.89088982e+10  4.25e-04 1.40e-05  3.50e-02   131s

 100   6.89090182e+10  6.89089120e+10  3.76e-04 1.18e-05  3.04e-02   133s

INFO:gurobipy: 100   6.89090182e+10  6.89089120e+10  3.76e-04 1.18e-05  3.04e-02   133s

 101   6.89090150e+10  6.89089253e+10  3.17e-04 9.84e-06  2.56e-02   134s

INFO:gurobipy: 101   6.89090150e+10  6.89089253e+10  3.17e-04 9.84e-06  2.56e-02   134s

 102   6.89090134e+10  6.89089368e+10  2.87e-04 8.27e-06  2.19e-02   135s

INFO:gurobipy: 102   6.89090134e+10  6.89089368e+10  2.87e-04 8.27e-06  2.19e-02   135s

 103   6.89090120e+10  6.89089412e+10  2.62e-04 7.66e-06  2.02e-02   137s

INFO:gurobipy: 103   6.89090120e+10  6.89089412e+10  2.62e-04 7.66e-06  2.02e-02   137s

INFO:gurobipy:

Barrier solved model in 103 iterations and 136.69 seconds (144.40 work units)

INFO:gurobipy:Barrier solved model in 103 iterations and 136.69 seconds (144.40 work units)

Optimal objective 6.89090120e+10

INFO:gurobipy:Optimal objective 6.89090120e+10

INFO:gurobipy:

Warning: environment still referenced so free is deferred (Continue to use WLS)

INFO:gurobipy:Warning: environment still referenced so free is deferred (Continue to use WLS)
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 1857166 primals, 5388059 duals
Objective: 6.89e+10
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Generator-ext-p-lower, Generator-ext-p-upper, Generator-fix-p-ramp_limit_up, Generator-fix-p-ramp_limit_down, Link-fix-p-lower, Link-fix-p-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-ext-p_dispatch-lower, StorageUnit-ext-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-ext-p_store-lower, StorageUnit-ext-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-ext-state_of_charge-lower, StorageUnit-ext-state_of_charge-upper, StorageUnit-energy_balance were not assigned to the network.

('ok', 'optimal')

In [30]:
n.optimize.fix_optimal_capacities()

In [31]:
n.generators

,bus,control,type,p_nom,p_nom_mod,p_nom_extendable,p_nom_min,p_nom_max,p_min_pu,p_max_pu,...,ramp_limit_up,ramp_limit_down,ramp_limit_start_up,ramp_limit_shut_down,weight,p_nom_opt,emission_activity_ratio,opex_fixed,max_utilisation_rate,min_utilisation_rate
Generator,,,,,,,,,,,,,,,,,,,,,
wind-offshore-unspecified:GRIDREGION-JPN-SH,GRIDREGION-JPN-SH,PQ,wind-offshore-unspecified,1981.999988,0.0,False,1700.0,1982.0,0.0,1.0,...,NaN,NaN,1.0,1.0,1.0,1981.999988,NaN,65507.74854,NaN,NaN
wind-offshore-unspecified:GRIDREGION-JPN-HR,GRIDREGION-JPN-HR,PQ,wind-offshore-unspecified,1300.000000,0.0,False,1300.0,1300.0,0.0,1.0,...,NaN,NaN,1.0,1.0,1.0,1300.000000,NaN,65507.74854,NaN,NaN
wind-offshore-unspecified:GRIDREGION-JPN-CB,GRIDREGION-JPN-CB,PQ,wind-offshore-unspecified,10377.999893,0.0,False,1350.0,10378.0,0.0,1.0,...,NaN,NaN,1.0,1.0,1.0,10377.999893,NaN,65507.74854,NaN,NaN
wind-offshore-unspecified:GRIDREGION-JPN-HK,GRIDREGION-JPN-HK,PQ,wind-offshore-unspecified,14650.000001,0.0,False,14650.0,45106.0,0.0,1.0,...,NaN,NaN,1.0,1.0,1.0,14650.000001,NaN,65507.74854,NaN,NaN
wind-offshore-unspecified:GRIDREGION-JPN-KA,GRIDREGION-JPN-KA,PQ,wind-offshore-unspecified,1149.999981,0.0,False,900.0,1150.0,0.0,1.0,...,NaN,NaN,1.0,1.0,1.0,1149.999981,NaN,65507.74854,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
gas-more-advanced-combined-cycle:GRIDREGION-JPN-CB,GRIDREGION-JPN-CB,PQ,gas-more-advanced-combined-cycle,2625.000000,0.0,False,0.0,inf,0.0,1.0,...,0.9,0.9,1.0,1.0,1.0,2625.000000,0.198,79141.06703,0.7,0.230
gas-more-advanced-combined-cycle:GRIDREGION-JPN-HR,GRIDREGION-JPN-HR,PQ,gas-more-advanced-combined-cycle,159.000000,0.0,False,0.0,inf,0.0,1.0,...,0.9,0.9,1.0,1.0,1.0,159.000000,0.198,79141.06703,0.7,0.100
gas-more-advanced-combined-cycle:GRIDREGION-JPN-KA,GRIDREGION-JPN-KA,PQ,gas-more-advanced-combined-cycle,2092.000000,0.0,False,0.0,inf,0.0,1.0,...,0.9,0.9,1.0,1.0,1.0,2092.000000,0.198,79141.06703,0.7,0.225
gas-more-advanced-combined-cycle:GRIDREGION-JPN-CG,GRIDREGION-JPN-CG,PQ,gas-more-advanced-combined-cycle,364.000000,0.0,False,0.0,inf,0.0,1.0,...,0.9,0.9,1.0,1.0,1.0,364.000000,0.198,79141.06703,0.7,0.050
gas-more-advanced-combined-cycle:GRIDREGION-JPN-KY,GRIDREGION-JPN-KY,PQ,gas-more-advanced-combined-cycle,400.000000,0.0,False,0.0,inf,0.0,1.0,...,0.9,0.9,1.0,1.0,1.0,400.000000,0.198,79141.06703,0.7,0.040

In [29]:
n.generators

,bus,control,type,p_nom,p_nom_mod,p_nom_extendable,p_nom_min,p_nom_max,p_min_pu,p_max_pu,...,ramp_limit_up,ramp_limit_down,ramp_limit_start_up,ramp_limit_shut_down,weight,p_nom_opt,emission_activity_ratio,opex_fixed,max_utilisation_rate,min_utilisation_rate
Generator,,,,,,,,,,,,,,,,,,,,,
wind-offshore-unspecified:GRIDREGION-JPN-SH,GRIDREGION-JPN-SH,PQ,wind-offshore-unspecified,1700.0,0.0,True,1700.0,1982.0,0.0,1.0,...,NaN,NaN,1.0,1.0,1.0,1981.999988,NaN,65507.74854,NaN,NaN
wind-offshore-unspecified:GRIDREGION-JPN-HR,GRIDREGION-JPN-HR,PQ,wind-offshore-unspecified,1300.0,0.0,True,1300.0,1300.0,0.0,1.0,...,NaN,NaN,1.0,1.0,1.0,1300.000000,NaN,65507.74854,NaN,NaN
wind-offshore-unspecified:GRIDREGION-JPN-CB,GRIDREGION-JPN-CB,PQ,wind-offshore-unspecified,1350.0,0.0,True,1350.0,10378.0,0.0,1.0,...,NaN,NaN,1.0,1.0,1.0,10377.999893,NaN,65507.74854,NaN,NaN
wind-offshore-unspecified:GRIDREGION-JPN-HK,GRIDREGION-JPN-HK,PQ,wind-offshore-unspecified,14650.0,0.0,True,14650.0,45106.0,0.0,1.0,...,NaN,NaN,1.0,1.0,1.0,14650.000001,NaN,65507.74854,NaN,NaN
wind-offshore-unspecified:GRIDREGION-JPN-KA,GRIDREGION-JPN-KA,PQ,wind-offshore-unspecified,900.0,0.0,True,900.0,1150.0,0.0,1.0,...,NaN,NaN,1.0,1.0,1.0,1149.999981,NaN,65507.74854,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
gas-more-advanced-combined-cycle:GRIDREGION-JPN-CB,GRIDREGION-JPN-CB,PQ,gas-more-advanced-combined-cycle,2625.0,0.0,False,0.0,inf,0.0,1.0,...,0.9,0.9,1.0,1.0,1.0,2625.000000,0.198,79141.06703,0.7,0.230
gas-more-advanced-combined-cycle:GRIDREGION-JPN-HR,GRIDREGION-JPN-HR,PQ,gas-more-advanced-combined-cycle,159.0,0.0,False,0.0,inf,0.0,1.0,...,0.9,0.9,1.0,1.0,1.0,159.000000,0.198,79141.06703,0.7,0.100
gas-more-advanced-combined-cycle:GRIDREGION-JPN-KA,GRIDREGION-JPN-KA,PQ,gas-more-advanced-combined-cycle,2092.0,0.0,False,0.0,inf,0.0,1.0,...,0.9,0.9,1.0,1.0,1.0,2092.000000,0.198,79141.06703,0.7,0.225
gas-more-advanced-combined-cycle:GRIDREGION-JPN-CG,GRIDREGION-JPN-CG,PQ,gas-more-advanced-combined-cycle,364.0,0.0,False,0.0,inf,0.0,1.0,...,0.9,0.9,1.0,1.0,1.0,364.000000,0.198,79141.06703,0.7,0.050
gas-more-advanced-combined-cycle:GRIDREGION-JPN-KY,GRIDREGION-JPN-KY,PQ,gas-more-advanced-combined-cycle,400.0,0.0,False,0.0,inf,0.0,1.0,...,0.9,0.9,1.0,1.0,1.0,400.000000,0.198,79141.06703,0.7,0.040

In [ ]:
n.buses_t.marginal_price.describe()

In [ ]:
n.statistics()

In [ ]:
n.export_to_netcdf("/home/jy/tz-amp/.amp/client-earth_CE-A-SEP7-PoC_alpha-9/platform_network.solved.nc")